const airlines = [
    {id:1,n:"DHL"},
    {id:2,n:"Aerolínea La Venezolana"},
    {id:3,n:"Conviasa"},
    {id:4,n:"Laser Airlines"},
    {id:5,n:"Aerolíneas Estelar Latinoamérica"},
    {id:6,n:"Turpial Airlines"},
    {id:7,n:"Albatros Airlines"},
    {id:8,n:"Copa Airlines"},
    {id:9,n:"Fly the World"},
    {id:10,n:"Aerotuy Airlines"},
    {id:11,n:"Aruba Airlines"},
    {id:12,n:"Rutaca Airlines"},
    {id:13,n:"Avior Airlines"},
    {id:14,n:"Turkis Airlines"},
    {id:15,n:"Tap Portugal"},
    {id:16,n:"Aerolilneas Argentinas"},
    {id:17,n:"Aeromexico"},
    {id:18,n:"Aeropostal"},
    {id:19,n:"Aerosucre"},
    {id:20,n:"Air Europa"},
    {id:21,n:"Airfrance"},
    {id:22,n:"Alitalia"},
    {id:23,n:"America Airlines"},
    {id:24,n:"Amerijet"},
    {id:25,n:"Aserca Airlines"},
    {id:26,n:"Caribbean Airlines"},
    {id:27,n:"Charter Internacional"},
    {id:28,n:"Charter Nacional"},
    {id:29,n:"Cubana de Aviación"},
    {id:30,n:"Delta Airlines"},
    {id:31,n:"DML"},
    {id:32,n:"Dynamic Airlines"},
    {id:33,n:"Easy Sky"},
    {id:34,n:"Fid Servi"},
    {id:35,n:"Iberia"},
    {id:36,n:"Insel Airlines"},
    {id:37,n:"Lan"},
    {id:38,n:"Lufthansa"},
    {id:39,n:"Oficial"},
    {id:40,n:"Rutaca"},
    {id:42,n:"Santa Barbara Airlines"},
    {id:43,n:"Skylease"},
    {id:44,n:"Solar Cargo"},
    {id:45,n:"Taca"},
    {id:46,n:"Tam"},
    {id:47,n:"Tame"},
    {id:48,n:"Transcarga"},
    {id:49,n:"Travel Service"},
    {id:50,n:"United Airlines"},
    {id:51,n:"Varig-gol"},
    {id:52,n:"Venezolana"},
    {id:53,n:"Vensecar"},
    {id:54,n:"White Airways"},
]
export default airlines;