const airport = [
    {id:91,nombre:"Aeropuerto Nacional de Anaco"},
    {id:92,nombre:"Aeropuerto Internacional José Antonio Anzoátegui"},
    {id:93,nombre:"Aeropuerto Don Edmundo Barrios"	},
    {id:94,nombre:"Aeropuerto de Guasdualito" },
    {id:95,nombre:"Aeropuerto de Elorza" 	},
    {id:96,nombre:"Aeropuerto de Palmarito" },
    {id:97,nombre:"Aeropuerto Nacional Las Flecheras"},
    {id:98,nombre:"Aeropuerto de Puerto Páez"},
    {id:99,nombre:"Aeropuerto Civil Florencio Gomez Base Escuela Mariscal Sucre"},
    {id:100,nombre:"Aeropuerto Internacional Palo Negro"},
    {id:101,nombre:"Aeropuerto Nacional de Barinas"},
    {id:102,nombre: "Aeropuerto de Santa Barbara De Barinas" },
    {id:103,nombre:"Aeropuerto Nacional Tomás de Heres"},
    {id:104,nombre:"Aeropuerto de Caicara del Orinoco"},
    {id:105,nombre:"Aeropuerto Armando Schwarck"},
    {id:106,nombre:"Aeropuerto Parque Nacional Canaima"},
    {id:107,nombre:"Aeropuerto de El Dorado"},
    {id:108,nombre:"Aeropuerto de Icabaru"},
    {id:109,nombre:"Aeropuerto de Kavanayen"},
    {id:110,nombre:"Aeropuerto de Kamarata"	},
    {id:111,nombre:"Aeropuerto de Maripa"},
    {id:112,nombre:"Aeropuerto Internacional Manuel Carlos Piar"},
    {id:113,nombre:"Aeropuerto Internacional de Santa Elena de Uairén"},
    {id:114,nombre:"Aeropuerto de Tumeremo"	},
    {id:115,nombre:"Aeropuerto de Uriman"},
    {id:116,nombre:"Aeropuerto de San Salvador"	},
    {id:117,nombre:"Aeropuerto de Wonken"	},
    {id:118,nombre:"Aeropuerto de Paraitepuy"},
    {id:119,nombre:"Aeropuerto Nacional Bartolomé Salom"},
    {id:120,nombre:"Aeropuerto Internacional Arturo Michelena"},
    {id:121,nombre:"Aeropuerto de San Carlos"},
    {id:122,nombre:"Aeropuerto de Pedernales"},
    {id:123,nombre:"Aeropuerto de Tucupita"},
    {id:124,nombre:"Aeropuerto de La Orchila"},
    {id:125,nombre:"Aeropuerto de Los Roques"},
    {id:126,nombre:"Aeropuerto Internacional José Leonardo Chirinos"},
    {id:127,nombre:"Aeropuerto de Churuguara"},
    {id:128,nombre:"Aeropuerto Internacional Josefa Camejo"},
    {id:129,nombre:"Aeropuerto de Calabozo"},
    {id:130,nombre:"Aeropuerto Nacional Valle La Pascua"},
    {id:131,nombre:"Aeropuerto de Altagracia de Orituco"},
    {id:132,nombre:"Aeropuerto de Zaraza"	},
    {id:133,nombre:"Aeropuerto Internacional Jacinto Lara"	},
    {id:134,nombre:"Aeropuerto de Carora"	},
    {id:135,nombre:"Aeropuerto Alberto Carnevalli"	},
    {id:136,nombre:"Aeropuerto Internacional Juan Pablo Pérez Alfonzo"},
    {id:137,nombre:"Aeropuerto de Lagunillas"	},
    {id:138,nombre:"Aeropuerto Caracas Oscar Machado Zuloaga"	},
    {id:139,nombre:"Base Aérea Generalísimo Francisco de Miranda"	},
    {id:140,nombre:"Aeropuerto de Higuerote" 	},
    {id:141,nombre:"Aeropuerto Metropolitano de Ocumare del Tuy"},
    {id:142,nombre:"Aeropuerto Internacional José Tadeo Monagas" 	},
    {id:143,nombre:"Aerpuerto Nacional de la Isla de Coche, Tcnel. Andrés Miguel Salazar Marcano"},
    {id:144,nombre:"Aeropuerto Internacional del Caribe, Santiago Mariño"},
    {id:145,nombre:"Aeropuerto Nacional Oswaldo Guevara Mujica" },
    {id:146,nombre:"Aeropuerto Nacional La Coromoto"},
    {id:147,nombre:"Aeropuerto Nacional José Francisco Bermúdez"},
    {id:148,nombre:"Aeropuerto Internacional Antonio José De Sucre"	},
    {id:149,nombre:"Aeropuerto Nacional de Güiria"	},
    {id:150,nombre:"Aeropuerto Nacional Francisco García de Hevia"	},
    {id:151,nombre:"Aeropuerto de Paramillo"	},
    {id:152,nombre:"Aeropuerto Internacional Juan Vicente Gómez"	},
    {id:153,nombre:"Aeropuerto Base Aérea Mayor Buenaventura Vivas"	},
    {id:154,nombre:"Aeropuerto de Boconó"	},
    {id:155,nombre:"Aeropuerto Antonio Nicolás Briceño"	},
    {id:156,nombre:"Aeropuerto Internacional Simón Bolívar"	},
    {id:157,nombre:"Aeropuerto Subteniente Nestor Arias"	},
    {id:158,nombre:"Aeropuerto de Bachaquero"	},
    {id:159,nombre:"Aeropuerto El Cubo"},
    {id:160,nombre:"Aeropuerto Internacional La Chinita"},
    {id:161,nombre:"Aeropuerto de Oro Negro"	},
    {id:162,nombre:"Aeropuerto Miguel Ángel Urdaneta Fernández"},
    {id:163,nombre:"Base Aérea El Libertador"},
]
export default airport;