const estado = [
    {id:'1', nombre:'DISTRITO CAPITAL'},
    {id:'2', nombre:'AMAZONAS'},
    {id:'3', nombre:'ANZOATEGUI'},
    {id:'4', nombre:'APURE'},
    {id:'5', nombre:'ARAGUA'},
    {id:'6', nombre:'BARINAS'},
    {id:'7', nombre:'BOLIVAR'},
    {id:'8', nombre:'CARABOBO'},
    {id:'9', nombre:'COJEDES'},
    {id:'10', nombre:'DELTA AMACURO'},
    {id:'11', nombre:'FALCON'},
    {id:'12', nombre:'GUARICO'},
    {id:'13', nombre:'LARA'},
    {id:'14', nombre:'MERIDA'},
    {id:'15', nombre:'BOLIVARIANO DE MIRANDA'},
    {id:'16', nombre:'MONAGAS'},
    {id:'17', nombre:'NUEVA ESPARTA'},
    {id:'18', nombre:'PORTUGUESA'},
    {id:'19', nombre:'SUCRE'},
    {id:'20', nombre:'TACHIRA'},
    {id:'21', nombre:'TRUJILLO'},
    {id:'22', nombre:'YARACUY'},
    {id:'23', nombre:'ZULIA'},
    {id:'24', nombre:'LA GUAIRA'},
    {id:'25', nombre:'DEPENDENCIAS FEDERALES'},
    {id:'26', nombre:'SIN INFORMACION'}
    ];
export default estado