const municipio = [
    {id:'1', nombre:'OBISPOS', id_estado: '6'},
    {id:'2', nombre:'PEDRAZA', id_estado: '6'},
    {id:'3', nombre:'ROJAS', id_estado: '6'},
    {id:'4', nombre:'SOSA', id_estado: '6'},
    {id:'5', nombre:'ANDRES ELOY BLANCO', id_estado: '6'},
    {id:'6', nombre:'CARONI', id_estado: '7'},
    {id:'7', nombre:'CEDEÑO', id_estado: '7'},
    {id:'8', nombre:'EL CALLAO', id_estado: '7'},
    {id:'9', nombre:'GRAN SABANA', id_estado: '7'},
    {id:'10', nombre:'HERES', id_estado: '7'},
    {id:'11', nombre:'PIAR', id_estado: '7'},
    {id:'12', nombre:'BOLIVARIANO ANGOSTURA', id_estado: '7'},
    {id:'13', nombre:'ROSCIO', id_estado: '7'},
    {id:'14', nombre:'SIFONTES', id_estado: '7'},
    {id:'15', nombre:'SUCRE', id_estado: '7'},
    {id:'16', nombre:'PADRE PEDRO CHIEN', id_estado: '7'},
    {id:'17', nombre:'BEJUMA', id_estado: '8'},
    {id:'18', nombre:'CARLOS ARVELO', id_estado: '8'},
    {id:'19', nombre:'DIEGO IBARRA', id_estado: '8'},
    {id:'20', nombre:'GUACARA', id_estado: '8'},
    {id:'21', nombre:'JUAN JOSE MORA', id_estado: '8'},
    {id:'22', nombre:'LIBERTADOR', id_estado: '8'},
    {id:'23', nombre:'LOS GUAYOS', id_estado: '8'},
    {id:'24', nombre:'ARAGUA', id_estado: '3'},
    {id:'25', nombre:'FERNANDO DE PEÑALVER', id_estado: '3'},
    {id:'26', nombre:'FRANCISCO DEL CARMEN CARVAJAL', id_estado: '3'},
    {id:'27', nombre:'ACHAGUAS', id_estado: '4'},
    {id:'28', nombre:'BIRUACA', id_estado: '4'},
    {id:'29', nombre:'MUÑOZ', id_estado: '4'},
    {id:'30', nombre:'PAEZ', id_estado: '4'},
    {id:'31', nombre:'PEDRO CAMEJO', id_estado: '4'},
    {id:'32', nombre:'ROMULO GALLEGOS', id_estado: '4'},
    {id:'33', nombre:'SAN FERNANDO', id_estado: '4'},
    {id:'34', nombre:'BOLIVAR', id_estado: '5'},
    {id:'35', nombre:'CAMATAGUA', id_estado: '5'},
    {id:'36', nombre:'GIRARDOT', id_estado: '5'},
    {id:'37', nombre:'JOSE ANGEL LAMAS', id_estado: '5'},
    {id:'38', nombre:'JOSE FELIX RIBAS', id_estado: '5'},
    {id:'39', nombre:'JOSE RAFAEL REVENGA', id_estado: '5'},
    {id:'40', nombre:'LIBERTADOR', id_estado: '5'},
    {id:'41', nombre:'MARIO BRICEÑO IRAGORRY', id_estado: '5'},
    {id:'42', nombre:'SAN CASIMIRO', id_estado: '5'},
    {id:'43', nombre:'SAN SEBASTIAN', id_estado: '5'},
    {id:'44', nombre:'SANTIAGO MARIÑO', id_estado: '5'},
    {id:'45', nombre:'SANTOS MICHELENA', id_estado: '5'},
    {id:'46', nombre:'SUCRE', id_estado: '5'},
    {id:'47', nombre:'TOVAR', id_estado: '5'},
    {id:'48', nombre:'URDANETA', id_estado: '5'},
    {id:'49', nombre:'ZAMORA', id_estado: '5'},
    {id:'50', nombre:'FRANCISCO LINARES ALCANTARA', id_estado: '5'},
    {id:'51', nombre:'OCUMARE DE LA COSTA DE ORO', id_estado: '5'},
    {id:'52', nombre:'ALBERTO ARVELO TORREALBA', id_estado: '6'},
    {id:'53', nombre:'ANTONIO JOSE DE SUCRE', id_estado: '6'},
    {id:'54', nombre:'ARISMENDI', id_estado: '6'},
    {id:'55', nombre:'BARINAS', id_estado: '6'},
    {id:'56', nombre:'BOLIVAR', id_estado: '6'},
    {id:'57', nombre:'CRUZ PAREDES', id_estado: '6'},
    {id:'58', nombre:'EZEQUIEL ZAMORA', id_estado: '6'},
    {id:'59', nombre:'CABIMAS', id_estado: '23'},
    {id:'60', nombre:'CATATUMBO', id_estado: '23'},
    {id:'61', nombre:'COLON', id_estado: '23'},
    {id:'62', nombre:'FRANCISCO JAVIER PULGAR', id_estado: '23'},
    {id:'63', nombre:'JESUS ENRIQUE LOSSADA', id_estado: '23'},
    {id:'64', nombre:'JESUS MARIA SEMPRUN', id_estado: '23'},
    {id:'65', nombre:'LA CAÑADA DE URDANETA', id_estado: '23'},
    {id:'66', nombre:'LAGUNILLAS', id_estado: '23'},
    {id:'67', nombre:'MACHIQUES DE PERIJA', id_estado: '23'},
    {id:'68', nombre:'MARA', id_estado: '23'},
    {id:'69', nombre:'MARACAIBO', id_estado: '23'},
    {id:'70', nombre:'MIRANDA', id_estado: '23'},
    {id:'71', nombre:'INDIGENA BOLIVARIANO GUAJIRA', id_estado: '23'},
    {id:'72', nombre:'ROSARIO DE PERIJA', id_estado: '23'},
    {id:'73', nombre:'SAN FRANCISCO', id_estado: '23'},
    {id:'74', nombre:'SANTA RITA', id_estado: '23'},
    {id:'75', nombre:'SIMON BOLIVAR', id_estado: '23'},
    {id:'76', nombre:'SUCRE', id_estado: '23'},
    {id:'77', nombre:'VALMORE RODRIGUEZ', id_estado: '23'},
    {id:'78', nombre:'VARGAS', id_estado: '24'},
    {id:'79', nombre:'DEPENDENCIAS FEDERALES', id_estado: '25'},
    {id:'80', nombre:'MIRANDA', id_estado: '8'},
    {id:'81', nombre:'MONTALBAN', id_estado: '8'},
    {id:'82', nombre:'NAGUANAGUA', id_estado: '8'},
    {id:'83', nombre:'PUERTO CABELLO', id_estado: '8'},
    {id:'84', nombre:'SAN DIEGO', id_estado: '8'},
    {id:'85', nombre:'SAN JOAQUIN', id_estado: '8'},
    {id:'86', nombre:'VALENCIA', id_estado: '8'},
    {id:'87', nombre:'ANZOATEGUI', id_estado: '9'},
    {id:'88', nombre:'TINAQUILLO', id_estado: '9'},
    {id:'89', nombre:'GIRARDOT', id_estado: '9'},
    {id:'90', nombre:'LIMA BLANCO', id_estado: '9'},
    {id:'91', nombre:'PAO DE SAN JUAN BAUTISTA', id_estado: '9'},
    {id:'92', nombre:'RICAURTE', id_estado: '9'},
    {id:'93', nombre:'ROMULO GALLEGOS', id_estado: '9'},
    {id:'94', nombre:'EZEQUIEL ZAMORA', id_estado: '9'},
    {id:'95', nombre:'TINACO', id_estado: '9'},
    {id:'96', nombre:'ANTONIO DIAZ', id_estado: '10'},
    {id:'97', nombre:'CASACOIMA', id_estado: '10'},
    {id:'98', nombre:'PEDERNALES', id_estado: '10'},
    {id:'99', nombre:'TUCUPITA', id_estado: '10'},
    {id:'100', nombre:'ACOSTA', id_estado: '11'},
    {id:'101', nombre:'BOLIVAR', id_estado: '11'},
    {id:'102', nombre:'BUCHIVACOA', id_estado: '11'},
    {id:'103', nombre:'CACIQUE MANAURE', id_estado: '11'},
    {id:'104', nombre:'CARIRUBANA', id_estado: '11'},
    {id:'105', nombre:'COLINA', id_estado: '11'},
    {id:'106', nombre:'DABAJURO', id_estado: '11'},
    {id:'107', nombre:'DEMOCRACIA', id_estado: '11'},
    {id:'108', nombre:'FALCON', id_estado: '11'},
    {id:'109', nombre:'FEDERACION', id_estado: '11'},
    {id:'110', nombre:'JACURA', id_estado: '11'},
    {id:'111', nombre:'LOS TAQUES', id_estado: '11'},
    {id:'112', nombre:'MAUROA', id_estado: '11'},
    {id:'113', nombre:'MIRANDA', id_estado: '11'},
    {id:'114', nombre:'MONSEÑOR ITURRIZA', id_estado: '11'},
    {id:'115', nombre:'PALMASOLA', id_estado: '11'},
    {id:'116', nombre:'PETIT', id_estado: '11'},
    {id:'117', nombre:'PIRITU', id_estado: '11'},
    {id:'118', nombre:'SAN FRANCISCO', id_estado: '11'},
    {id:'119', nombre:'SILVA', id_estado: '11'},
    {id:'120', nombre:'SUCRE', id_estado: '11'},
    {id:'121', nombre:'TOCOPERO', id_estado: '11'},
    {id:'122', nombre:'UNION', id_estado: '11'},
    {id:'123', nombre:'URUMACO', id_estado: '11'},
    {id:'124', nombre:'ZAMORA', id_estado: '11'},
    {id:'125', nombre:'CAMAGUAN', id_estado: '12'},
    {id:'126', nombre:'CHAGUARAMAS', id_estado: '12'},
    {id:'127', nombre:'EL SOCORRO', id_estado: '12'},
    {id:'128', nombre:'CAJIGAL', id_estado: '19'},
    {id:'129', nombre:'SAN GERONIMO DE GUAYABAL', id_estado: '12'},
    {id:'130', nombre:'LEONARDO INFANTE', id_estado: '12'},
    {id:'131', nombre:'LAS MERCEDES', id_estado: '12'},
    {id:'132', nombre:'BARALT', id_estado: '23'},
    {id:'133', nombre:'JULIAN MELLADO', id_estado: '12'},
    {id:'134', nombre:'FRANCISCO DE MIRANDA', id_estado: '12'},
    {id:'135', nombre:'JOSE TADEO MONAGAS', id_estado: '12'},
    {id:'136', nombre:'ORTIZ', id_estado: '12'},
    {id:'137', nombre:'JOSE FELIX RIBAS', id_estado: '12'},
    {id:'138', nombre:'JUAN GERMAN ROSCIO', id_estado: '12'},
    {id:'139', nombre:'SAN JOSE DE GUARIBE', id_estado: '12'},
    {id:'140', nombre:'SANTA MARIA DE IPIRE', id_estado: '12'},
    {id:'141', nombre:'PEDRO ZARAZA', id_estado: '12'},
    {id:'142', nombre:'ANDRES ELOY BLANCO', id_estado: '13'},
    {id:'143', nombre:'CRESPO', id_estado: '13'},
    {id:'144', nombre:'IRIBARREN', id_estado: '13'},
    {id:'145', nombre:'JIMENEZ', id_estado: '13'},
    {id:'146', nombre:'MORAN', id_estado: '13'},
    {id:'147', nombre:'PALAVECINO', id_estado: '13'},
    {id:'148', nombre:'SIMON PLANAS', id_estado: '13'},
    {id:'149', nombre:'TORRES', id_estado: '13'},
    {id:'150', nombre:'URDANETA', id_estado: '13'},
    {id:'151', nombre:'ALBERTO ADRIANI', id_estado: '14'},
    {id:'152', nombre:'ANDRES BELLO', id_estado: '14'},
    {id:'153', nombre:'ANTONIO PINTO SALINAS', id_estado: '14'},
    {id:'154', nombre:'FRANCISCO DE MIRANDA', id_estado: '3'},
    {id:'155', nombre:'GUANTA', id_estado: '3'},
    {id:'156', nombre:'INDEPENDENCIA', id_estado: '3'},
    {id:'157', nombre:'JUAN ANTONIO SOTILLO', id_estado: '3'},
    {id:'158', nombre:'JUAN MANUEL CAJIGAL', id_estado: '3'},
    {id:'159', nombre:'JOSE GREGORIO MONAGAS', id_estado: '3'},
    {id:'160', nombre:'LIBERTAD', id_estado: '3'},
    {id:'161', nombre:'MANUEL EZEQUIEL BRUZUAL', id_estado: '3'},
    {id:'162', nombre:'PEDRO MARIA FREITES', id_estado: '3'},
    {id:'163', nombre:'PIRITU', id_estado: '3'},
    {id:'164', nombre:'SAN JOSE DE GUANIPA', id_estado: '3'},
    {id:'165', nombre:'SAN JUAN DE CAPISTRANO', id_estado: '3'},
    {id:'166', nombre:'SANTA ANA', id_estado: '3'},
    {id:'167', nombre:'SIMON BOLIVAR', id_estado: '3'},
    {id:'168', nombre:'SIMON RODRIGUEZ', id_estado: '3'},
    {id:'169', nombre:'SIR ARTHUR MC GREGOR', id_estado: '3'},
    {id:'170', nombre:'ARICAGUA', id_estado: '14'},
    {id:'171', nombre:'ARZOBISPO CHACON', id_estado: '14'},
    {id:'172', nombre:'CAMPO ELIAS', id_estado: '14'},
    {id:'173', nombre:'CARACCIOLO PARRA OLMEDO', id_estado: '14'},
    {id:'174', nombre:'CARDENAL QUINTERO', id_estado: '14'},
    {id:'175', nombre:'GUARAQUE', id_estado: '14'},
    {id:'176', nombre:'JULIO CESAR SALAS', id_estado: '14'},
    {id:'177', nombre:'JUSTO BRICEÑO', id_estado: '14'},
    {id:'178', nombre:'LIBERTADOR', id_estado: '14'},
    {id:'179', nombre:'MIRANDA', id_estado: '14'},
    {id:'180', nombre:'OBISPO RAMOS DE LORA', id_estado: '14'},
    {id:'181', nombre:'PADRE NOGUERA', id_estado: '14'},
    {id:'182', nombre:'PUEBLO LLANO', id_estado: '14'},
    {id:'183', nombre:'RANGEL', id_estado: '14'},
    {id:'184', nombre:'RIVAS DAVILA', id_estado: '14'},
    {id:'185', nombre:'SANTOS MARQUINA', id_estado: '14'},
    {id:'186', nombre:'SUCRE', id_estado: '14'},
    {id:'187', nombre:'TOVAR', id_estado: '14'},
    {id:'188', nombre:'TULIO FEBRES CORDERO', id_estado: '14'},
    {id:'189', nombre:'ACEVEDO', id_estado: '15'},
    {id:'190', nombre:'ANDRES BELLO', id_estado: '15'},
    {id:'191', nombre:'BARUTA', id_estado: '15'},
    {id:'192', nombre:'BRION', id_estado: '15'},
    {id:'193', nombre:'BUROZ', id_estado: '15'},
    {id:'194', nombre:'CARRIZAL', id_estado: '15'},
    {id:'195', nombre:'CHACAO', id_estado: '15'},
    {id:'196', nombre:'CRISTOBAL ROJAS', id_estado: '15'},
    {id:'197', nombre:'EL HATILLO', id_estado: '15'},
    {id:'198', nombre:'BOLIVARIANO GUAICAIPURO', id_estado: '15'},
    {id:'199', nombre:'INDEPENDENCIA', id_estado: '15'},
    {id:'200', nombre:'LANDER', id_estado: '15'},
    {id:'201', nombre:'LOS SALIAS', id_estado: '15'},
    {id:'202', nombre:'PAEZ', id_estado: '15'},
    {id:'203', nombre:'PAZ CASTILLO', id_estado: '15'},
    {id:'204', nombre:'PEDRO GUAL', id_estado: '15'},
    {id:'205', nombre:'PLAZA', id_estado: '15'},
    {id:'206', nombre:'SIMON BOLIVAR', id_estado: '15'},
    {id:'207', nombre:'SUCRE', id_estado: '15'},
    {id:'208', nombre:'URDANETA', id_estado: '15'},
    {id:'209', nombre:'ZAMORA', id_estado: '15'},
    {id:'210', nombre:'ACOSTA', id_estado: '16'},
    {id:'211', nombre:'AGUASAY', id_estado: '16'},
    {id:'212', nombre:'BOLIVAR', id_estado: '16'},
    {id:'213', nombre:'CARIPE', id_estado: '16'},
    {id:'214', nombre:'CEDEÑO', id_estado: '16'},
    {id:'215', nombre:'EZEQUIEL ZAMORA', id_estado: '16'},
    {id:'216', nombre:'LIBERTADOR', id_estado: '16'},
    {id:'217', nombre:'MATURIN', id_estado: '16'},
    {id:'218', nombre:'PIAR', id_estado: '16'},
    {id:'219', nombre:'PUNCERES', id_estado: '16'},
    {id:'220', nombre:'SANTA BARBARA', id_estado: '16'},
    {id:'221', nombre:'SOTILLO', id_estado: '16'},
    {id:'222', nombre:'URACOA', id_estado: '16'},
    {id:'223', nombre:'ANTOLIN DEL CAMPO', id_estado: '17'},
    {id:'224', nombre:'ARISMENDI', id_estado: '17'},
    {id:'225', nombre:'DIAZ', id_estado: '17'},
    {id:'226', nombre:'GARCIA', id_estado: '17'},
    {id:'227', nombre:'GOMEZ', id_estado: '17'},
    {id:'228', nombre:'MANEIRO', id_estado: '17'},
    {id:'229', nombre:'MARCANO', id_estado: '17'},
    {id:'230', nombre:'MARIÑO', id_estado: '17'},
    {id:'231', nombre:'PENINSULA DE MACANAO', id_estado: '17'},
    {id:'232', nombre:'TUBORES', id_estado: '17'},
    {id:'233', nombre:'VILLALBA', id_estado: '17'},
    {id:'234', nombre:'AGUA BLANCA', id_estado: '18'},
    {id:'235', nombre:'ARAURE', id_estado: '18'},
    {id:'236', nombre:'ESTELLER', id_estado: '18'},
    {id:'237', nombre:'GUANARE', id_estado: '18'},
    {id:'238', nombre:'GUANARITO', id_estado: '18'},
    {id:'239', nombre:'MONSEÑOR JOSE VICENTE DE UNDA', id_estado: '18'},
    {id:'240', nombre:'OSPINO', id_estado: '18'},
    {id:'241', nombre:'TURISTICO DIEGO BAUTISTA URBANEJA', id_estado: '3'},
    {id:'242', nombre:'PAEZ', id_estado: '18'},
    {id:'243', nombre:'PAPELON', id_estado: '18'},
    {id:'244', nombre:'SAN GENARO DE BOCONOITO', id_estado: '18'},
    {id:'245', nombre:'SAN RAFAEL DE ONOTO', id_estado: '18'},
    {id:'246', nombre:'SANTA ROSALIA', id_estado: '18'},
    {id:'247', nombre:'SUCRE', id_estado: '18'},
    {id:'248', nombre:'TUREN', id_estado: '18'},
    {id:'249', nombre:'ANDRES ELOY BLANCO', id_estado: '19'},
    {id:'250', nombre:'ANDRES MATA', id_estado: '19'},
    {id:'251', nombre:'ARISMENDI', id_estado: '19'},
    {id:'252', nombre:'BENITEZ', id_estado: '19'},
    {id:'253', nombre:'BERMUDEZ', id_estado: '19'},
    {id:'254', nombre:'BOLIVAR', id_estado: '19'},
    {id:'255', nombre:'CRUZ SALMERON ACOSTA', id_estado: '19'},
    {id:'256', nombre:'LIBERTADOR', id_estado: '19'},
    {id:'257', nombre:'MARIÑO', id_estado: '19'},
    {id:'258', nombre:'MEJIA', id_estado: '19'},
    {id:'259', nombre:'MONTES', id_estado: '19'},
    {id:'260', nombre:'RIBERO', id_estado: '19'},
    {id:'261', nombre:'SUCRE', id_estado: '19'},
    {id:'262', nombre:'VALDEZ', id_estado: '19'},
    {id:'263', nombre:'ANDRES BELLO', id_estado: '20'},
    {id:'264', nombre:'ANTONIO ROMULO COSTA', id_estado: '20'},
    {id:'265', nombre:'AYACUCHO', id_estado: '20'},
    {id:'266', nombre:'BOLIVAR', id_estado: '20'},
    {id:'267', nombre:'CARDENAS', id_estado: '20'},
    {id:'268', nombre:'CORDOBA', id_estado: '20'},
    {id:'269', nombre:'FERNANDEZ FEO', id_estado: '20'},
    {id:'270', nombre:'FRANCISCO DE MIRANDA', id_estado: '20'},
    {id:'271', nombre:'GARCIA DE HEVIA', id_estado: '20'},
    {id:'272', nombre:'GUASIMOS', id_estado: '20'},
    {id:'273', nombre:'INDEPENDENCIA', id_estado: '20'},
    {id:'274', nombre:'JAUREGUI', id_estado: '20'},
    {id:'275', nombre:'JOSE MARIA VARGAS', id_estado: '20'},
    {id:'276', nombre:'JUNIN', id_estado: '20'},
    {id:'277', nombre:'LIBERTAD', id_estado: '20'},
    {id:'278', nombre:'LIBERTADOR', id_estado: '20'},
    {id:'279', nombre:'LOBATERA', id_estado: '20'},
    {id:'280', nombre:'MICHELENA', id_estado: '20'},
    {id:'281', nombre:'PANAMERICANO', id_estado: '20'},
    {id:'282', nombre:'PEDRO MARIA UREÑA', id_estado: '20'},
    {id:'283', nombre:'RAFAEL URDANETA', id_estado: '20'},
    {id:'284', nombre:'SAMUEL DARIO MALDONADO', id_estado: '20'},
    {id:'285', nombre:'SAN CRISTOBAL', id_estado: '20'},
    {id:'286', nombre:'SEBORUCO', id_estado: '20'},
    {id:'287', nombre:'SIMON RODRIGUEZ', id_estado: '20'},
    {id:'288', nombre:'SUCRE', id_estado: '20'},
    {id:'289', nombre:'TORBES', id_estado: '20'},
    {id:'290', nombre:'URIBANTE', id_estado: '20'},
    {id:'291', nombre:'SAN JUDAS TADEO', id_estado: '20'},
    {id:'292', nombre:'ANDRES BELLO', id_estado: '21'},
    {id:'293', nombre:'BOCONO', id_estado: '21'},
    {id:'294', nombre:'BOLIVAR', id_estado: '21'},
    {id:'295', nombre:'CANDELARIA', id_estado: '21'},
    {id:'296', nombre:'CARACHE', id_estado: '21'},
    {id:'297', nombre:'ESCUQUE', id_estado: '21'},
    {id:'298', nombre:'JOSE FELIPE MARQUEZ CAÑIZALES', id_estado: '21'},
    {id:'299', nombre:'JUAN VICENTE CAMPO ELIAS', id_estado: '21'},
    {id:'300', nombre:'LA CEIBA', id_estado: '21'},
    {id:'301', nombre:'MIRANDA', id_estado: '21'},
    {id:'302', nombre:'MONTE CARMELO', id_estado: '21'},
    {id:'303', nombre:'MOTATAN', id_estado: '21'},
    {id:'304', nombre:'PAMPAN', id_estado: '21'},
    {id:'305', nombre:'PAMPANITO', id_estado: '21'},
    {id:'306', nombre:'RAFAEL RANGEL', id_estado: '21'},
    {id:'307', nombre:'SAN RAFAEL DE CARVAJAL', id_estado: '21'},
    {id:'308', nombre:'SUCRE', id_estado: '21'},
    {id:'309', nombre:'TRUJILLO', id_estado: '21'},
    {id:'310', nombre:'URDANETA', id_estado: '21'},
    {id:'311', nombre:'VALERA', id_estado: '21'},
    {id:'312', nombre:'ARISTIDES BASTIDAS', id_estado: '22'},
    {id:'313', nombre:'BOLIVAR', id_estado: '22'},
    {id:'314', nombre:'BRUZUAL', id_estado: '22'},
    {id:'315', nombre:'COCOROTE', id_estado: '22'},
    {id:'316', nombre:'INDEPENDENCIA', id_estado: '22'},
    {id:'317', nombre:'JOSE ANTONIO PAEZ', id_estado: '22'},
    {id:'318', nombre:'LA TRINIDAD', id_estado: '22'},
    {id:'319', nombre:'MANUEL MONGE', id_estado: '22'},
    {id:'320', nombre:'NIRGUA', id_estado: '22'},
    {id:'321', nombre:'PEÑA', id_estado: '22'},
    {id:'322', nombre:'SAN FELIPE', id_estado: '22'},
    {id:'323', nombre:'SUCRE', id_estado: '22'},
    {id:'324', nombre:'URACHICHE', id_estado: '22'},
    {id:'325', nombre:'VEROES', id_estado: '22'},
    {id:'326', nombre:'ALMIRANTE PADILLA', id_estado: '23'},
    {id:'327', nombre:'ZEA', id_estado: '14'},
    {id:'328', nombre:'BOLIVARIANO LIBERTADOR', id_estado: '1'},
    {id:'329', nombre:'AUTONOMO ALTO ORINOCO', id_estado: '2'},
    {id:'330', nombre:'AUTONOMO ATABAPO', id_estado: '2'},
    {id:'331', nombre:'AUTONOMO ATURES', id_estado: '2'},
    {id:'332', nombre:'AUTONOMO AUTANA', id_estado: '2'},
    {id:'333', nombre:'AUTONOMO MAROA', id_estado: '2'},
    {id:'334', nombre:'AUTONOMO MANAPIARE', id_estado: '2'},
    {id:'335', nombre:'AUTONOMO RIO NEGRO', id_estado: '2'},
    {id:'336', nombre:'ANACO ANACO', id_estado: '3'}
    ];
export default municipio;