const parroquia = [
    {idparroquia: 1, nombre:'23 DE ENERO', idmunicipio: '328'},
    {idparroquia: 2, nombre:'BUENA VISTA', idmunicipio: '336'},
    {idparroquia: 3, nombre:'URBANA ACHAGUAS', idmunicipio: '27'},
    {idparroquia: 4, nombre:'APURITO', idmunicipio: '27'},
    {idparroquia: 5, nombre:'MANTECAL', idmunicipio: '29'},
    {idparroquia: 6, nombre:'ARAMENDI', idmunicipio: '30'},
    {idparroquia: 7, nombre:'CODAZZI', idmunicipio: '31'},
    {idparroquia: 8, nombre:'LA TRINIDAD', idmunicipio: '32'},
    {idparroquia: 9, nombre:'CINCO DE JULIO', idmunicipio: '6'},
    {idparroquia: 10, nombre:'ESTÁNQUES', idmunicipio: '186'},
    {idparroquia: 11, nombre:'LA TRAMPA', idmunicipio: '186'},
    {idparroquia: 12, nombre:'PUEBLO NUEVO DEL SUR', idmunicipio: '186'},
    {idparroquia: 13, nombre:'SAN JUAN', idmunicipio: '186'},
    {idparroquia: 14, nombre:'EL LLANO', idmunicipio: '187'},
    {idparroquia: 15, nombre:'SAN FRANCISCO', idmunicipio: '187'},
    {idparroquia: 16, nombre:'TOVAR', idmunicipio: '187'},
    {idparroquia: 17, nombre:'INDEPENDENCIA', idmunicipio: '188'},
    {idparroquia: 18, nombre:'MARÍA DE LA CONCEPCIÓN PALACIOS BLANCO', idmunicipio: '188'},
    {idparroquia: 19, nombre:'SANTA APOLONIA', idmunicipio: '188'},
    {idparroquia: 20, nombre:'CAÑO EL TIGRE', idmunicipio: '327'},
    {idparroquia: 21, nombre:'CAPITAL ACOSTA', idmunicipio: '210'},
    {idparroquia: 22, nombre:'SAN FRANCISCO', idmunicipio: '210'},
    {idparroquia: 23, nombre:'VICENTE FUENTES', idmunicipio: '233'},
    {idparroquia: 24, nombre:'CARIACO', idmunicipio: '260'},
    {idparroquia: 25, nombre:'AGUSTÍN CODAZZI', idmunicipio: '62'},
    {idparroquia: 26, nombre:'EL DANTO', idmunicipio: '66'},
    {idparroquia: 27, nombre:'JOSÉ ANTONIO CHAVES', idmunicipio: '70'},
    {idparroquia: 28, nombre:'JUNÍN', idmunicipio: '308'},
    {idparroquia: 29, nombre:'GRAN ROQUE', idmunicipio: '79'},
    {idparroquia: 30, nombre:'LOS TESTIGOS', idmunicipio: '79'},
    {idparroquia: 31, nombre:'CHIMANAS', idmunicipio: '79'},
    {idparroquia: 32, nombre:'EL RECREO', idmunicipio: '33'},
    {idparroquia: 33, nombre:'BIDEAU', idmunicipio: '262'},
    {idparroquia: 34, nombre:'EL VALLE', idmunicipio: '328'},
    {idparroquia: 35, nombre:'NO URBANA LAS GUACAMAYAS', idmunicipio: '38'},
    {idparroquia: 36, nombre:'SAN CASIMIRO', idmunicipio: '42'},
    {idparroquia: 37, nombre:'NO TIENE PARROQUIA', idmunicipio: '121'},
    {idparroquia: 38, nombre:'ZABALA', idmunicipio: '225'},
    {idparroquia: 39, nombre:'NO TIENE PARROQUIA', idmunicipio: '270'},
    {idparroquia: 40, nombre:'SALOM', idmunicipio: '320'},
    {idparroquia: 41, nombre:'LA PASTORA', idmunicipio: '328'},
    {idparroquia: 42, nombre:'LA VEGA', idmunicipio: '328'},
    {idparroquia: 43, nombre:'MACARAO', idmunicipio: '328'},
    {idparroquia: 44, nombre:'SAN AGUSTÍN', idmunicipio: '328'},
    {idparroquia: 45, nombre:'SAN BERNARDINO', idmunicipio: '328'},
    {idparroquia: 46, nombre:'SAN JOSÉ', idmunicipio: '328'},
    {idparroquia: 47, nombre:'NO TIENE PARROQUIA', idmunicipio: '319'},
    {idparroquia: 48, nombre:'SAN JUAN', idmunicipio: '328'},
    {idparroquia: 49, nombre:'SAN PEDRO', idmunicipio: '328'},
    {idparroquia: 50, nombre:'SANTA ROSALÍA', idmunicipio: '328'},
    {idparroquia: 51, nombre:'SANTA TERESA', idmunicipio: '328'},
    {idparroquia: 52, nombre:'SUCRE', idmunicipio: '328'},
    {idparroquia: 53, nombre:'HUACHAMACARE', idmunicipio: '329'},
    {idparroquia: 54, nombre:'MARAWAKA', idmunicipio: '329'},
    {idparroquia: 55, nombre:'MAVACA', idmunicipio: '329'},
    {idparroquia: 56, nombre:'SIERRA PARIMA', idmunicipio: '329'},
    {idparroquia: 57, nombre:'UCATA', idmunicipio: '330'},
    {idparroquia: 58, nombre:'YAPACANA', idmunicipio: '330'},
    {idparroquia: 59, nombre:'CANAME', idmunicipio: '330'},
    {idparroquia: 60, nombre:'FERNANDO GIRÓN TOVAR', idmunicipio: '331'},
    {idparroquia: 61, nombre:'LUIS ALBERTO GÓMEZ', idmunicipio: '331'},
    {idparroquia: 62, nombre:'PARHUEÑA', idmunicipio: '331'},
    {idparroquia: 63, nombre:'PLATANILLAL', idmunicipio: '331'},
    {idparroquia: 64, nombre:'SAMARIAPO', idmunicipio: '332'},
    {idparroquia: 65, nombre:'SIPAPO', idmunicipio: '332'},
    {idparroquia: 66, nombre:'MUNDUAPO', idmunicipio: '332'},
    {idparroquia: 67, nombre:'GUAYAPO', idmunicipio: '332'},
    {idparroquia: 68, nombre:'VICTORINO', idmunicipio: '333'},
    {idparroquia: 69, nombre:'COMUNIDAD', idmunicipio: '333'},
    {idparroquia: 70, nombre:'ALTO VENTUARI', idmunicipio: '334'},
    {idparroquia: 71, nombre:'MEDIO VENTUARI', idmunicipio: '334'},
    {idparroquia: 72, nombre:'BAJO VENTUARI', idmunicipio: '334'},
    {idparroquia: 73, nombre:'SOLANO', idmunicipio: '335'},
    {idparroquia: 74, nombre:'CASIQUIARE', idmunicipio: '335'},
    {idparroquia: 75, nombre:'COCUY', idmunicipio: '335'},
    {idparroquia: 76, nombre:'CAPITAL ANACO', idmunicipio: '336'},
    {idparroquia: 77, nombre:'SAN JOAQUÍN', idmunicipio: '336'},
    {idparroquia: 78, nombre:'CAPITAL ARAGUA', idmunicipio: '24'},
    {idparroquia: 79, nombre:'CACHIPO', idmunicipio: '24'},
    {idparroquia: 80, nombre:'CAPITAL FERNANDO DE PEÑALVER', idmunicipio: '25'},
    {idparroquia: 81, nombre:'SAN MIGUEL', idmunicipio: '25'},
    {idparroquia: 82, nombre:'SUCRE', idmunicipio: '25'},
    {idparroquia: 83, nombre:'CAPITAL FRANCISCO DEL CARMEN CARVAJAL', idmunicipio: '26'},
    {idparroquia: 84, nombre:'SANTA BÁRBARA', idmunicipio: '26'},
    {idparroquia: 85, nombre:'CAPITAL FRANCISCO DE MIRANDA', idmunicipio: '154'},
    {idparroquia: 86, nombre:'ATAPIRIRE', idmunicipio: '154'},
    {idparroquia: 87, nombre:'BOCA DEL PAO', idmunicipio: '154'},
    {idparroquia: 88, nombre:'EL PAO', idmunicipio: '154'},
    {idparroquia: 89, nombre:'MÚCURA', idmunicipio: '154'},
    {idparroquia: 90, nombre:'CAPITAL GUANTA', idmunicipio: '155'},
    {idparroquia: 91, nombre:'CHORRERÓN', idmunicipio: '155'},
    {idparroquia: 92, nombre:'CAPITAL INDEPENDENCIA', idmunicipio: '156'},
    {idparroquia: 93, nombre:'MAMO', idmunicipio: '156'},
    {idparroquia: 94, nombre:'CAPITAL PUERTO LA CRUZ', idmunicipio: '157'},
    {idparroquia: 95, nombre:'POZUELOS', idmunicipio: '157'},
    {idparroquia: 96, nombre:'CAPITAL JUAN MANUEL CAJIGAL', idmunicipio: '158'},
    {idparroquia: 97, nombre:'SAN PABLO', idmunicipio: '158'},
    {idparroquia: 98, nombre:'CAPITAL JOSÉ GREGORIO MONAGAS', idmunicipio: '159'},
    {idparroquia: 99, nombre:'PIAR', idmunicipio: '159'},
    {idparroquia: 100, nombre:'SAN DIEGO DE CABRUTICA', idmunicipio: '159'},
    {idparroquia: 101, nombre:'SANTA CLARA', idmunicipio: '159'},
    {idparroquia: 102, nombre:'UVERITO', idmunicipio: '159'},
    {idparroquia: 103, nombre:'ZUATA', idmunicipio: '159'},
    {idparroquia: 104, nombre:'CAPITAL LIBERTAD', idmunicipio: '160'},
    {idparroquia: 105, nombre:'EL CARITO', idmunicipio: '160'},
    {idparroquia: 106, nombre:'SANTA INÉS', idmunicipio: '160'},
    {idparroquia: 107, nombre:'CAPITAL MANUEL EZEQUIEL BRUZUAL', idmunicipio: '161'},
    {idparroquia: 108, nombre:'GUANAPE', idmunicipio: '161'},
    {idparroquia: 109, nombre:'SABANA DE UCHIRE', idmunicipio: '161'},
    {idparroquia: 110, nombre:'CAPITAL PEDRO MARÍA FRÉITES', idmunicipio: '162'},
    {idparroquia: 111, nombre:'LIBERTADOR', idmunicipio: '162'},
    {idparroquia: 112, nombre:'SANTA ROSA', idmunicipio: '162'},
    {idparroquia: 113, nombre:'URICA', idmunicipio: '162'},
    {idparroquia: 114, nombre:'CAPITAL PÍRITU', idmunicipio: '163'},
    {idparroquia: 115, nombre:'SAN FRANCISCO', idmunicipio: '163'},
    {idparroquia: 116, nombre:'NO TIENE PARROQUIA', idmunicipio: '164'},
    {idparroquia: 117, nombre:'CAPITAL SAN JUAN DE CAPISTRANO', idmunicipio: '165'},
    {idparroquia: 118, nombre:'BOCA DE CHÁVEZ', idmunicipio: '165'},
    {idparroquia: 119, nombre:'CAPITAL SANTA ANA', idmunicipio: '166'},
    {idparroquia: 120, nombre:'PUEBLO NUEVO', idmunicipio: '166'},
    {idparroquia: 121, nombre:'EL CARMEN', idmunicipio: '167'},
    {idparroquia: 122, nombre:'SAN CRISTÓBAL', idmunicipio: '167'},
    {idparroquia: 123, nombre:'BERGANTÍN', idmunicipio: '167'},
    {idparroquia: 124, nombre:'CAIGUA', idmunicipio: '167'},
    {idparroquia: 125, nombre:'EL PILAR', idmunicipio: '167'},
    {idparroquia: 126, nombre:'NARICUAL', idmunicipio: '167'},
    {idparroquia: 127, nombre:'EDMUNDO BARRIOS', idmunicipio: '168'},
    {idparroquia: 128, nombre:'MIGUEL OTERO SILVA', idmunicipio: '168'},
    {idparroquia: 129, nombre:'CAPITAL SIR ARTHUR MC GREGOR', idmunicipio: '169'},
    {idparroquia: 130, nombre:'TOMÁS ALFARO CALATRAVA', idmunicipio: '169'},
    {idparroquia: 131, nombre:'CAPITAL DIEGO BAUTISTA URBANEJA', idmunicipio: '241'},
    {idparroquia: 132, nombre:'EL MORRO', idmunicipio: '241'},
    {idparroquia: 133, nombre:'EL YAGUAL', idmunicipio: '27'},
    {idparroquia: 134, nombre:'GUACHARA', idmunicipio: '27'},
    {idparroquia: 135, nombre:'MUCURITAS EL', idmunicipio: '27'},
    {idparroquia: 136, nombre:'QUESERAS DEL MEDIO', idmunicipio: '27'},
    {idparroquia: 137, nombre:'URBANA BIRUACA', idmunicipio: '28'},
    {idparroquia: 138, nombre:'COCHE', idmunicipio: '328'},
    {idparroquia: 139, nombre:'URBANA BRUZUAL', idmunicipio: '29'},
    {idparroquia: 140, nombre:'QUINTERO', idmunicipio: '29'},
    {idparroquia: 141, nombre:'RINCÓN HONDO', idmunicipio: '29'},
    {idparroquia: 142, nombre:'SAN VICENTE', idmunicipio: '29'},
    {idparroquia: 143, nombre:'URBANA GUASDUALITO', idmunicipio: '30'},
    {idparroquia: 144, nombre:'EL AMPARO', idmunicipio: '30'},
    {idparroquia: 145, nombre:'SAN CAMILO', idmunicipio: '30'},
    {idparroquia: 146, nombre:'URDANETA', idmunicipio: '30'},
    {idparroquia: 147, nombre:'URBANA SAN JUAN DE PAYARA', idmunicipio: '31'},
    {idparroquia: 148, nombre:'CUNAVICHE', idmunicipio: '31'},
    {idparroquia: 149, nombre:'URBANA ELORZA', idmunicipio: '32'},
    {idparroquia: 150, nombre:'URBANA SAN FERNANDO', idmunicipio: '33'},
    {idparroquia: 151, nombre:'PEÑALVER', idmunicipio: '33'},
    {idparroquia: 152, nombre:'SAN RAFAEL DE ATAMAICA', idmunicipio: '33'},
    {idparroquia: 153, nombre:'NO TIENE PARROQUIA', idmunicipio: '34'},
    {idparroquia: 154, nombre:'CAMATAGUA', idmunicipio: '35'},
    {idparroquia: 155, nombre:'NO URBANA CARMEN DE CURA', idmunicipio: '35'},
    {idparroquia: 156, nombre:'NO URBANA CHORONÍ', idmunicipio: '36'},
    {idparroquia: 157, nombre:'URBANA LAS DELICIAS', idmunicipio: '36'},
    {idparroquia: 158, nombre:'URBANA MADRE MARÍA DE SAN JOSÉ', idmunicipio: '36'},
    {idparroquia: 159, nombre:'URBANA JOAQUÍN CRESPO', idmunicipio: '36'},
    {idparroquia: 160, nombre:'URBANA PEDRO JOSÉ OVALLES', idmunicipio: '36'},
    {idparroquia: 161, nombre:'URBANA JOSÉ CASANOVA GODOY', idmunicipio: '36'},
    {idparroquia: 162, nombre:'URBANA ANDRÉS ELOY BLANCO', idmunicipio: '36'},
    {idparroquia: 163, nombre:'URBANA LOS TACARIGUAS', idmunicipio: '36'},
    {idparroquia: 164, nombre:'NO TIENE PARROQUIA', idmunicipio: '37'},
    {idparroquia: 165, nombre:'URBANA JUAN VICENTE BOLÍVAR Y PONTE', idmunicipio: '38'},
    {idparroquia: 166, nombre:'URBANA CASTOR NIEVES RÍOS', idmunicipio: '38'},
    {idparroquia: 167, nombre:'CANDELARIA', idmunicipio: '328'},
    {idparroquia: 168, nombre:'CARICUAO', idmunicipio: '328'},
    {idparroquia: 169, nombre:'CATEDRAL', idmunicipio: '328'},
    {idparroquia: 170, nombre:'EL JUNQUITO', idmunicipio: '328'},
    {idparroquia: 171, nombre:'EL PARAISO', idmunicipio: '328'},
    {idparroquia: 172, nombre:'EL RECREO', idmunicipio: '328'},
    {idparroquia: 173, nombre:'NO URBANA PAO DE ZÁRATE', idmunicipio: '38'},
    {idparroquia: 174, nombre:'NO URBANA ZUATA', idmunicipio: '38'},
    {idparroquia: 175, nombre:'NO TIENE PARROQUIA', idmunicipio: '39'},
    {idparroquia: 176, nombre:'LIBERTADOR', idmunicipio: '40'},
    {idparroquia: 177, nombre:'NO URBANA SAN MARTÍN DE PORRES', idmunicipio: '40'},
    {idparroquia: 178, nombre:'MARIO BRICEÑO IRAGORRY', idmunicipio: '41'},
    {idparroquia: 179, nombre:'URBANA CAÑA DE AZÚCAR', idmunicipio: '41'},
    {idparroquia: 180, nombre:'NO URBANA', idmunicipio: '42'},
    {idparroquia: 181, nombre:'NO URBANA OLLAS DE CARAMACATE', idmunicipio: '42'},
    {idparroquia: 182, nombre:'NO URBANA VALLE MORÍN', idmunicipio: '42'},
    {idparroquia: 183, nombre:'NO TIENE PARROQUIA', idmunicipio: '43'},
    {idparroquia: 184, nombre:'SANTIAGO MARIÑO', idmunicipio: '44'},
    {idparroquia: 185, nombre:'NO URBANA ARÉVALO APONTE', idmunicipio: '44'},
    {idparroquia: 186, nombre:'NO URBANA CHUAO', idmunicipio: '44'},
    {idparroquia: 187, nombre:'NO URBANA SAMÁN DE GÜERE', idmunicipio: '44'},
    {idparroquia: 188, nombre:'NO URBANA ALFREDO PACHECO MIRANDA', idmunicipio: '44'},
    {idparroquia: 189, nombre:'SANTOS MICHELENA', idmunicipio: '45'},
    {idparroquia: 190, nombre:'NO URBANA TIARA', idmunicipio: '45'},
    {idparroquia: 191, nombre:'SUCRE', idmunicipio: '46'},
    {idparroquia: 192, nombre:'NO URBANA BELLA VISTA', idmunicipio: '46'},
    {idparroquia: 193, nombre:'NO TIENE PARROQUIA', idmunicipio: '47'},
    {idparroquia: 194, nombre:'URDANETA', idmunicipio: '48'},
    {idparroquia: 195, nombre:'NO URBANA LAS PEÑITAS', idmunicipio: '48'},
    {idparroquia: 196, nombre:'NO URBANA SAN FRANCISCO DE CARA', idmunicipio: '48'},
    {idparroquia: 197, nombre:'NO URBANA TAGUAY', idmunicipio: '48'},
    {idparroquia: 198, nombre:'ZAMORA', idmunicipio: '49'},
    {idparroquia: 199, nombre:'NO URBANA MAGDALENO', idmunicipio: '49'},
    {idparroquia: 200, nombre:'NO URBANA SAN FRANCISCO DE ASÍS', idmunicipio: '49'},
    {idparroquia: 201, nombre:'NO URBANA VALLES DE TUCUTUNEMO', idmunicipio: '49'},
    {idparroquia: 202, nombre:'NO URBANA AUGUSTO MIJARES', idmunicipio: '49'},
    {idparroquia: 203, nombre:'FRANCISCO LINARES ALCÁNTARA', idmunicipio: '50'},
    {idparroquia: 204, nombre:'NO URBANA FRANCISCO DE MIRANDA', idmunicipio: '50'},
    {idparroquia: 205, nombre:'NO URBANA MONSEÑOR FELICIANO GONZÁLEZ', idmunicipio: '50'},
    {idparroquia: 206, nombre:'NO TIENE PARROQUIA', idmunicipio: '51'},
    {idparroquia: 207, nombre:'SABANETA', idmunicipio: '52'},
    {idparroquia: 208, nombre:'RODRÍGUEZ DOMÍNGUEZ', idmunicipio: '52'},
    {idparroquia: 209, nombre:'TICOPORO', idmunicipio: '53'},
    {idparroquia: 210, nombre:'ANDRÉS BELLO', idmunicipio: '53'},
    {idparroquia: 211, nombre:'NICOLÁS PULIDO', idmunicipio: '53'},
    {idparroquia: 212, nombre:'ARISMENDI', idmunicipio: '54'},
    {idparroquia: 213, nombre:'GUADARRAMA', idmunicipio: '54'},
    {idparroquia: 214, nombre:'LA UNIÓN', idmunicipio: '54'},
    {idparroquia: 215, nombre:'SAN ANTONIO', idmunicipio: '54'},
    {idparroquia: 216, nombre:'BARINAS', idmunicipio: '55'},
    {idparroquia: 217, nombre:'ALFREDO ARVELO LARRIVA', idmunicipio: '55'},
    {idparroquia: 218, nombre:'SAN SILVESTRE', idmunicipio: '55'},
    {idparroquia: 219, nombre:'SANTA INÉS', idmunicipio: '55'},
    {idparroquia: 220, nombre:'SANTA LUCÍA', idmunicipio: '55'},
    {idparroquia: 221, nombre:'TORUNOS', idmunicipio: '55'},
    {idparroquia: 222, nombre:'EL CARMEN', idmunicipio: '55'},
    {idparroquia: 223, nombre:'DON RÓMULO BETANCOURT', idmunicipio: '55'},
    {idparroquia: 224, nombre:'CORAZÓN DE JESÚS', idmunicipio: '55'},
    {idparroquia: 225, nombre:'RAMÓN IGNACIO MÉNDEZ', idmunicipio: '55'},
    {idparroquia: 226, nombre:'ALTO BARINAS', idmunicipio: '55'},
    {idparroquia: 227, nombre:'MANUEL PALACIO FAJARDO', idmunicipio: '55'},
    {idparroquia: 228, nombre:'JUAN ANTONIO RODRÍGUEZ DOMÍNGUEZ', idmunicipio: '55'},
    {idparroquia: 229, nombre:'DOMINGA ORTIZ DE PÁEZ', idmunicipio: '55'},
    {idparroquia: 230, nombre:'BARINITAS', idmunicipio: '56'},
    {idparroquia: 231, nombre:'ALTAMIRA', idmunicipio: '56'},
    {idparroquia: 232, nombre:'CALDERAS', idmunicipio: '56'},
    {idparroquia: 233, nombre:'BARRANCAS', idmunicipio: '57'},
    {idparroquia: 234, nombre:'EL SOCORRO', idmunicipio: '57'},
    {idparroquia: 235, nombre:'MASPARRITO', idmunicipio: '57'},
    {idparroquia: 236, nombre:'SANTA BÁRBARA', idmunicipio: '58'},
    {idparroquia: 237, nombre:'JOSÉ IGNACIO DEL PUMAR', idmunicipio: '58'},
    {idparroquia: 238, nombre:'PEDRO BRICEÑO MÉNDEZ', idmunicipio: '58'},
    {idparroquia: 239, nombre:'RAMÓN IGNACIO MÉNDEZ', idmunicipio: '58'},
    {idparroquia: 240, nombre:'OBISPOS', idmunicipio: '1'},
    {idparroquia: 241, nombre:'EL REAL', idmunicipio: '1'},
    {idparroquia: 242, nombre:'LA LUZ', idmunicipio: '1'},
    {idparroquia: 243, nombre:'LOS GUASIMITOS', idmunicipio: '1'},
    {idparroquia: 244, nombre:'CIUDAD BOLIVIA', idmunicipio: '2'},
    {idparroquia: 245, nombre:'IGNACIO BRICEÑO', idmunicipio: '2'},
    {idparroquia: 246, nombre:'JOSÉ FÉLIX RIBAS', idmunicipio: '2'},
    {idparroquia: 247, nombre:'PÁEZ', idmunicipio: '2'},
    {idparroquia: 248, nombre:'LIBERTAD', idmunicipio: '3'},
    {idparroquia: 249, nombre:'DOLORES', idmunicipio: '3'},
    {idparroquia: 250, nombre:'PALACIOS FAJARDO', idmunicipio: '3'},
    {idparroquia: 251, nombre:'SANTA ROSA', idmunicipio: '3'},
    {idparroquia: 252, nombre:'SIMÓN RODRÍGUEZ', idmunicipio: '3'},
    {idparroquia: 253, nombre:'CIUDAD DE NUTRIAS', idmunicipio: '4'},
    {idparroquia: 254, nombre:'EL REGALO', idmunicipio: '4'},
    {idparroquia: 255, nombre:'PUERTO DE NUTRIAS', idmunicipio: '4'},
    {idparroquia: 256, nombre:'SANTA CATALINA', idmunicipio: '4'},
    {idparroquia: 257, nombre:'SIMÓN BOLÍVAR', idmunicipio: '4'},
    {idparroquia: 258, nombre:'EL CANTÓN', idmunicipio: '5'},
    {idparroquia: 259, nombre:'SANTA CRUZ DE GUACAS', idmunicipio: '5'},
    {idparroquia: 260, nombre:'PUERTO VIVAS', idmunicipio: '5'},
    {idparroquia: 261, nombre:'CACHAMAY', idmunicipio: '6'},
    {idparroquia: 262, nombre:'CHIRICA', idmunicipio: '6'},
    {idparroquia: 263, nombre:'DALLA COSTA', idmunicipio: '6'},
    {idparroquia: 264, nombre:'ONCE DE ABRIL', idmunicipio: '6'},
    {idparroquia: 265, nombre:'SUCRE', idmunicipio: '89'},
    {idparroquia: 266, nombre:'SIMÓN BOLÍVAR', idmunicipio: '6'},
    {idparroquia: 267, nombre:'UNARE', idmunicipio: '6'},
    {idparroquia: 268, nombre:'UNIVERSIDAD', idmunicipio: '6'},
    {idparroquia: 269, nombre:'VISTA AL SOL', idmunicipio: '6'},
    {idparroquia: 270, nombre:'POZO VERDE', idmunicipio: '6'},
    {idparroquia: 271, nombre:'YOCOIMA', idmunicipio: '6'},
    {idparroquia: 272, nombre:'SECCIÓN CAPITAL CEDEÑO', idmunicipio: '7'},
    {idparroquia: 273, nombre:'ASCENSIÓN FARRERAS', idmunicipio: '7'},
    {idparroquia: 274, nombre:'GUANIAMO', idmunicipio: '7'},
    {idparroquia: 275, nombre:'LA URBANA', idmunicipio: '7'},
    {idparroquia: 276, nombre:'PIJIGUAOS', idmunicipio: '7'},
    {idparroquia: 277, nombre:'NO TIENE PARROQUIA', idmunicipio: '8'},
    {idparroquia: 278, nombre:'SECCIÓN CAPITAL GRAN SABANA', idmunicipio: '9'},
    {idparroquia: 279, nombre:'IKABARÚ', idmunicipio: '9'},
    {idparroquia: 280, nombre:'AGUA SALADA', idmunicipio: '10'},
    {idparroquia: 281, nombre:'JOSÉ ANTONIO PÁEZ', idmunicipio: '10'},
    {idparroquia: 282, nombre:'LA SABANITA', idmunicipio: '10'},
    {idparroquia: 283, nombre:'MARHUANTA', idmunicipio: '10'},
    {idparroquia: 284, nombre:'VISTA HERMOSA', idmunicipio: '10'},
    {idparroquia: 285, nombre:'ORINOCO', idmunicipio: '10'},
    {idparroquia: 286, nombre:'PANAPANA', idmunicipio: '10'},
    {idparroquia: 287, nombre:'ZEA', idmunicipio: '10'},
    {idparroquia: 288, nombre:'SECCIÓN CAPITAL PIAR', idmunicipio: '11'},
    {idparroquia: 289, nombre:'ANDRÉS ELOY BLANCO', idmunicipio: '11'},
    {idparroquia: 290, nombre:'PEDRO COVA', idmunicipio: '11'},
    {idparroquia: 291, nombre:'SECCIÓN CAPITAL ANGOSTURA', idmunicipio: '12'},
    {idparroquia: 292, nombre:'BARCELONETA', idmunicipio: '12'},
    {idparroquia: 293, nombre:'SAN FRANCISCO', idmunicipio: '12'},
    {idparroquia: 294, nombre:'SANTA BÁRBARA', idmunicipio: '12'},
    {idparroquia: 295, nombre:'SECCIÓN CAPITAL ROSCIO', idmunicipio: '13'},
    {idparroquia: 296, nombre:'SALOM', idmunicipio: '13'},
    {idparroquia: 297, nombre:'SECCIÓN CAPITAL SIFONTES', idmunicipio: '14'},
    {idparroquia: 298, nombre:'DALLA COSTA', idmunicipio: '14'},
    {idparroquia: 299, nombre:'SAN ISIDRO', idmunicipio: '14'},
    {idparroquia: 300, nombre:'SECCIÓN CAPITAL SUCRE', idmunicipio: '15'},
    {idparroquia: 301, nombre:'ARIPAO', idmunicipio: '15'},
    {idparroquia: 302, nombre:'GUARATARO', idmunicipio: '15'},
    {idparroquia: 303, nombre:'LAS MAJADAS', idmunicipio: '15'},
    {idparroquia: 304, nombre:'MOITACO', idmunicipio: '15'},
    {idparroquia: 305, nombre:'NO TIENE PARROQUIA', idmunicipio: '16'},
    {idparroquia: 306, nombre:'URBANA BEJUMA', idmunicipio: '17'},
    {idparroquia: 307, nombre:'NO URBANA CANOABO', idmunicipio: '17'},
    {idparroquia: 308, nombre:'CATEDRAL', idmunicipio: '10'},
    {idparroquia: 309, nombre:'NO URBANA SIMÓN BOLÍVAR', idmunicipio: '17'},
    {idparroquia: 310, nombre:'URBANA GÜIGÜE', idmunicipio: '18'},
    {idparroquia: 311, nombre:'NO URBANA BELÉN', idmunicipio: '18'},
    {idparroquia: 312, nombre:'NO URBANA TACARIGUA', idmunicipio: '18'},
    {idparroquia: 313, nombre:'URBANA AGUAS CALIENTES', idmunicipio: '19'},
    {idparroquia: 314, nombre:'URBANA MARIARA', idmunicipio: '19'},
    {idparroquia: 315, nombre:'URBANA CIUDAD ALIANZA', idmunicipio: '20'},
    {idparroquia: 316, nombre:'URBANA GUACARA', idmunicipio: '20'},
    {idparroquia: 317, nombre:'NO URBANA YAGUA', idmunicipio: '20'},
    {idparroquia: 318, nombre:'URBANA MORÓN', idmunicipio: '21'},
    {idparroquia: 319, nombre:'NO URBANA URAMA', idmunicipio: '21'},
    {idparroquia: 320, nombre:'URBANA TOCUYITO', idmunicipio: '22'},
    {idparroquia: 321, nombre:'URBANA INDEPENDENCIA', idmunicipio: '22'},
    {idparroquia: 322, nombre:'URBANA LOS GUAYOS', idmunicipio: '23'},
    {idparroquia: 323, nombre:'URBANA MIRANDA', idmunicipio: '80'},
    {idparroquia: 324, nombre:'URBANA MONTALBÁN', idmunicipio: '81'},
    {idparroquia: 325, nombre:'URBANA NAGUANAGUA', idmunicipio: '82'},
    {idparroquia: 326, nombre:'URBANA BARTOLOMÉ SALOM', idmunicipio: '83'},
    {idparroquia: 327, nombre:'URBANA DEMOCRACIA', idmunicipio: '83'},
    {idparroquia: 328, nombre:'URBANA FRATERNIDAD', idmunicipio: '83'},
    {idparroquia: 329, nombre:'URBANA GOAIGOAZA', idmunicipio: '83'},
    {idparroquia: 330, nombre:'URBANA JUAN JOSÉ FLORES', idmunicipio: '83'},
    {idparroquia: 331, nombre:'URBANA UNIÓN', idmunicipio: '83'},
    {idparroquia: 332, nombre:'NO URBANA BORBURATA', idmunicipio: '83'},
    {idparroquia: 333, nombre:'NO URBANA PATANEMO', idmunicipio: '83'},
    {idparroquia: 334, nombre:'URBANA SAN DIEGO', idmunicipio: '84'},
    {idparroquia: 335, nombre:'URBANA SAN JOAQUÍN', idmunicipio: '85'},
    {idparroquia: 336, nombre:'URBANA CANDELARIA', idmunicipio: '86'},
    {idparroquia: 337, nombre:'URBANA CATEDRAL', idmunicipio: '86'},
    {idparroquia: 338, nombre:'URBANA EL SOCORRO', idmunicipio: '86'},
    {idparroquia: 339, nombre:'URBANA MIGUEL PEÑA', idmunicipio: '86'},
    {idparroquia: 340, nombre:'URBANA RAFAEL URDANETA', idmunicipio: '86'},
    {idparroquia: 341, nombre:'URBANA SAN BLAS', idmunicipio: '86'},
    {idparroquia: 342, nombre:'URBANA SAN JOSÉ', idmunicipio: '86'},
    {idparroquia: 343, nombre:'URBANA SANTA ROSA', idmunicipio: '86'},
    {idparroquia: 344, nombre:'NO URBANA NEGRO PRIMERO', idmunicipio: '86'},
    {idparroquia: 345, nombre:'COJEDES', idmunicipio: '87'},
    {idparroquia: 346, nombre:'JUAN DE MATA SUÁREZ', idmunicipio: '87'},
    {idparroquia: 347, nombre:'TINAQUILLO', idmunicipio: '88'},
    {idparroquia: 348, nombre:'EL BAÚL', idmunicipio: '89'},
    {idparroquia: 349, nombre:'MACAPO', idmunicipio: '90'},
    {idparroquia: 350, nombre:'LA AGUADITA', idmunicipio: '90'},
    {idparroquia: 351, nombre:'EL PAO', idmunicipio: '91'},
    {idparroquia: 352, nombre:'LIBERTAD DE COJEDES', idmunicipio: '92'},
    {idparroquia: 353, nombre:'EL AMPARO', idmunicipio: '92'},
    {idparroquia: 354, nombre:'RÓMULO GALLEGOS', idmunicipio: '93'},
    {idparroquia: 355, nombre:'SAN CARLOS DE AUSTRIA', idmunicipio: '94'},
    {idparroquia: 356, nombre:'JUAN ÁNGEL BRAVO', idmunicipio: '94'},
    {idparroquia: 357, nombre:'MANUEL MANRIQUE', idmunicipio: '94'},
    {idparroquia: 358, nombre:'GENERAL EN JEFE JOSÉ LAURENCIO SILVA', idmunicipio: '95'},
    {idparroquia: 359, nombre:'CURIAPO', idmunicipio: '96'},
    {idparroquia: 360, nombre:'ALMIRANTE LUIS BRIÓN', idmunicipio: '96'},
    {idparroquia: 361, nombre:'FRANCISCO ANICETO LUGO', idmunicipio: '96'},
    {idparroquia: 362, nombre:'MANUEL RENAUD', idmunicipio: '96'},
    {idparroquia: 363, nombre:'PADRE BARRAL', idmunicipio: '96'},
    {idparroquia: 364, nombre:'SANTOS DE ABELGAS', idmunicipio: '96'},
    {idparroquia: 365, nombre:'IMATACA', idmunicipio: '97'},
    {idparroquia: 366, nombre:'CINCO DE JULIO', idmunicipio: '97'},
    {idparroquia: 367, nombre:'JUAN BAUTISTA ARISMENDI', idmunicipio: '97'},
    {idparroquia: 368, nombre:'MANUEL PIAR', idmunicipio: '97'},
    {idparroquia: 369, nombre:'RÓMULO GALLEGOS', idmunicipio: '97'},
    {idparroquia: 370, nombre:'PEDERNALES', idmunicipio: '98'},
    {idparroquia: 371, nombre:'LUIS BELTRÁN PRIETO FIGUEROA', idmunicipio: '98'},
    {idparroquia: 372, nombre:'SAN JOSÉ', idmunicipio: '99'},
    {idparroquia: 373, nombre:'JOSÉ VIDAL MARCANO', idmunicipio: '99'},
    {idparroquia: 374, nombre:'JUAN MILLÁN', idmunicipio: '99'},
    {idparroquia: 375, nombre:'LEONARDO RUÍZ PINEDA', idmunicipio: '99'},
    {idparroquia: 376, nombre:'MARISCAL ANTONIO JOSÉ DE SUCRE', idmunicipio: '99'},
    {idparroquia: 377, nombre:'MONSEÑOR ARGIMIRO GARCÍA', idmunicipio: '99'},
    {idparroquia: 378, nombre:'SAN RAFAEL', idmunicipio: '99'},
    {idparroquia: 379, nombre:'VIRGEN DEL VALLE', idmunicipio: '99'},
    {idparroquia: 380, nombre:'SAN JUAN DE LOS CAYOS', idmunicipio: '100'},
    {idparroquia: 381, nombre:'CAPADARE', idmunicipio: '100'},
    {idparroquia: 382, nombre:'LA PASTORA', idmunicipio: '100'},
    {idparroquia: 383, nombre:'LIBERTADOR', idmunicipio: '100'},
    {idparroquia: 384, nombre:'SAN LUIS', idmunicipio: '101'},
    {idparroquia: 385, nombre:'ARACUA', idmunicipio: '101'},
    {idparroquia: 386, nombre:'LA PEÑA', idmunicipio: '101'},
    {idparroquia: 387, nombre:'CAPATÁRIDA', idmunicipio: '102'},
    {idparroquia: 388, nombre:'BARIRO', idmunicipio: '102'},
    {idparroquia: 389, nombre:'BOROJÓ', idmunicipio: '102'},
    {idparroquia: 390, nombre:'GUAJIRO', idmunicipio: '102'},
    {idparroquia: 391, nombre:'SEQUE', idmunicipio: '102'},
    {idparroquia: 392, nombre:'ZAZÁRIDA', idmunicipio: '102'},
    {idparroquia: 393, nombre:'NO TIENE PARROQUIA', idmunicipio: '103'},
    {idparroquia: 394, nombre:'CARIRUBANA', idmunicipio: '104'},
    {idparroquia: 395, nombre:'NORTE', idmunicipio: '104'},
    {idparroquia: 396, nombre:'PUNTA CARDÓN', idmunicipio: '104'},
    {idparroquia: 397, nombre:'SANTA ANA', idmunicipio: '104'},
    {idparroquia: 398, nombre:'LA VELA DE CORO', idmunicipio: '105'},
    {idparroquia: 399, nombre:'ACURIGUA', idmunicipio: '105'},
    {idparroquia: 400, nombre:'GUAIBACOA', idmunicipio: '105'},
    {idparroquia: 401, nombre:'LAS CALDERAS', idmunicipio: '105'},
    {idparroquia: 402, nombre:'MACORUCA', idmunicipio: '105'},
    {idparroquia: 403, nombre:'NO TIENE PARROQUIA', idmunicipio: '106'},
    {idparroquia: 404, nombre:'PEDREGAL', idmunicipio: '107'},
    {idparroquia: 405, nombre:'AGUA CLARA', idmunicipio: '107'},
    {idparroquia: 406, nombre:'AVARIA', idmunicipio: '107'},
    {idparroquia: 407, nombre:'PIEDRA GRANDE', idmunicipio: '107'},
    {idparroquia: 408, nombre:'PURURECHE', idmunicipio: '107'},
    {idparroquia: 409, nombre:'PUEBLO NUEVO', idmunicipio: '108'},
    {idparroquia: 410, nombre:'ADÍCORA', idmunicipio: '108'},
    {idparroquia: 411, nombre:'BARAIVED', idmunicipio: '108'},
    {idparroquia: 412, nombre:'BUENA VISTA', idmunicipio: '108'},
    {idparroquia: 413, nombre:'JADACAQUIVA', idmunicipio: '108'},
    {idparroquia: 414, nombre:'MORUY', idmunicipio: '108'},
    {idparroquia: 415, nombre:'ADAURE', idmunicipio: '108'},
    {idparroquia: 416, nombre:'EL HATO', idmunicipio: '108'},
    {idparroquia: 417, nombre:'EL VÍNCULO', idmunicipio: '108'},
    {idparroquia: 418, nombre:'CHURUGUARA', idmunicipio: '109'},
    {idparroquia: 419, nombre:'AGUA LARGA', idmunicipio: '109'},
    {idparroquia: 420, nombre:'EL PAUJÍ', idmunicipio: '109'},
    {idparroquia: 421, nombre:'INDEPENDENCIA', idmunicipio: '109'},
    {idparroquia: 422, nombre:'MAPARARÍ', idmunicipio: '109'},
    {idparroquia: 423, nombre:'JACURA', idmunicipio: '110'},
    {idparroquia: 424, nombre:'AGUA LINDA', idmunicipio: '110'},
    {idparroquia: 425, nombre:'ARAURIMA', idmunicipio: '110'},
    {idparroquia: 426, nombre:'LOS TAQUES', idmunicipio: '111'},
    {idparroquia: 427, nombre:'JUDIBANA', idmunicipio: '111'},
    {idparroquia: 428, nombre:'MENE DE MAUROA', idmunicipio: '112'},
    {idparroquia: 429, nombre:'CASIGUA', idmunicipio: '112'},
    {idparroquia: 430, nombre:'SAN FÉLIX', idmunicipio: '112'},
    {idparroquia: 431, nombre:'SAN ANTONIO', idmunicipio: '113'},
    {idparroquia: 432, nombre:'SAN GABRIEL', idmunicipio: '113'},
    {idparroquia: 433, nombre:'SANTA ANA', idmunicipio: '113'},
    {idparroquia: 434, nombre:'GUZMÁN GUILLERMO', idmunicipio: '113'},
    {idparroquia: 435, nombre:'MITARE', idmunicipio: '113'},
    {idparroquia: 436, nombre:'RÍO SECO', idmunicipio: '113'},
    {idparroquia: 437, nombre:'SABANETA', idmunicipio: '113'},
    {idparroquia: 438, nombre:'CHICHIRIVICHE', idmunicipio: '114'},
    {idparroquia: 439, nombre:'BOCA DE TOCUYO', idmunicipio: '114'},
    {idparroquia: 440, nombre:'TOCUYO DE LA COSTA', idmunicipio: '114'},
    {idparroquia: 441, nombre:'NO TIENE PARROQUIA', idmunicipio: '115'},
    {idparroquia: 442, nombre:'CABURE', idmunicipio: '116'},
    {idparroquia: 443, nombre:'COLINA', idmunicipio: '116'},
    {idparroquia: 444, nombre:'CURIMAGUA', idmunicipio: '116'},
    {idparroquia: 445, nombre:'PÍRITU', idmunicipio: '117'},
    {idparroquia: 446, nombre:'SAN JOSÉ DE LA COSTA', idmunicipio: '117'},
    {idparroquia: 447, nombre:'NO TIENE PARROQUIA', idmunicipio: '118'},
    {idparroquia: 448, nombre:'TUCACAS', idmunicipio: '119'},
    {idparroquia: 449, nombre:'BOCA DE AROA', idmunicipio: '119'},
    {idparroquia: 450, nombre:'SUCRE', idmunicipio: '120'},
    {idparroquia: 451, nombre:'PECAYA', idmunicipio: '120'},
    {idparroquia: 452, nombre:'SANTA CRUZ DE BUCARAL', idmunicipio: '122'},
    {idparroquia: 453, nombre:'EL CHARAL', idmunicipio: '122'},
    {idparroquia: 454, nombre:'LAS VEGAS DEL TUY', idmunicipio: '122'},
    {idparroquia: 455, nombre:'URUMACO', idmunicipio: '123'},
    {idparroquia: 456, nombre:'BRUZUAL', idmunicipio: '123'},
    {idparroquia: 457, nombre:'PUERTO CUMAREBO', idmunicipio: '124'},
    {idparroquia: 458, nombre:'LA CIÉNAGA', idmunicipio: '124'},
    {idparroquia: 459, nombre:'LA SOLEDAD', idmunicipio: '124'},
    {idparroquia: 460, nombre:'PUEBLO CUMAREBO', idmunicipio: '124'},
    {idparroquia: 461, nombre:'ZAZÁRIDA', idmunicipio: '124'},
    {idparroquia: 462, nombre:'CAPITAL CAMAGUÁN', idmunicipio: '125'},
    {idparroquia: 463, nombre:'PUERTO MIRANDA', idmunicipio: '125'},
    {idparroquia: 464, nombre:'UVERITO', idmunicipio: '125'},
    {idparroquia: 465, nombre:'CHAGUARAMAS', idmunicipio: '126'},
    {idparroquia: 466, nombre:'EL SOCORRO', idmunicipio: '127'},
    {idparroquia: 467, nombre:'CAPITAL SAN GERÓNIMO DE GUAYABAL', idmunicipio: '129'},
    {idparroquia: 468, nombre:'CAZORLA', idmunicipio: '129'},
    {idparroquia: 469, nombre:'CAPITAL VALLE DE LA PASCUA', idmunicipio: '130'},
    {idparroquia: 470, nombre:'ESPINO', idmunicipio: '130'},
    {idparroquia: 471, nombre:'CAPITAL LAS MERCEDES', idmunicipio: '131'},
    {idparroquia: 472, nombre:'CABRUTA', idmunicipio: '131'},
    {idparroquia: 473, nombre:'SANTA RITA DE MANAPIRE', idmunicipio: '131'},
    {idparroquia: 474, nombre:'CAPITAL EL SOMBRERO', idmunicipio: '133'},
    {idparroquia: 475, nombre:'SOSA', idmunicipio: '133'},
    {idparroquia: 476, nombre:'CAPITAL CALABOZO', idmunicipio: '134'},
    {idparroquia: 477, nombre:'EL CALVARIO', idmunicipio: '134'},
    {idparroquia: 478, nombre:'EL RASTRO', idmunicipio: '134'},
    {idparroquia: 479, nombre:'GUARDATINAJAS', idmunicipio: '134'},
    {idparroquia: 480, nombre:'CAPITAL ALTAGRACIA DE ORITUCO', idmunicipio: '135'},
    {idparroquia: 481, nombre:'LEZAMA', idmunicipio: '135'},
    {idparroquia: 482, nombre:'LIBERTAD DE ORITUCO', idmunicipio: '135'},
    {idparroquia: 483, nombre:'PASO REAL DE MACAIRA', idmunicipio: '135'},
    {idparroquia: 484, nombre:'SAN FRANCISCO DE MACAIRA', idmunicipio: '135'},
    {idparroquia: 485, nombre:'SAN RAFAEL DE ORITUCO', idmunicipio: '135'},
    {idparroquia: 486, nombre:'SOUBLETTE', idmunicipio: '135'},
    {idparroquia: 487, nombre:'CAPITAL ORTIZ', idmunicipio: '136'},
    {idparroquia: 488, nombre:'SAN FRANCISCO DE TIZNADO', idmunicipio: '136'},
    {idparroquia: 489, nombre:'SAN JOSÉ DE TIZNADO', idmunicipio: '136'},
    {idparroquia: 490, nombre:'SAN LORENZO DE TIZNADO', idmunicipio: '136'},
    {idparroquia: 491, nombre:'CAPITAL TUCUPIDO', idmunicipio: '137'},
    {idparroquia: 492, nombre:'SAN RAFAEL DE LAYA', idmunicipio: '137'},
    {idparroquia: 493, nombre:'CAPITAL SAN JUAN DE LOS MORROS', idmunicipio: '138'},
    {idparroquia: 494, nombre:'CANTAGALLO', idmunicipio: '138'},
    {idparroquia: 495, nombre:'PARAPARA', idmunicipio: '138'},
    {idparroquia: 496, nombre:'SAN JOSÉ DE GUARIBE', idmunicipio: '139'},
    {idparroquia: 497, nombre:'CAPITAL SANTA MARÍA DE IPIRE', idmunicipio: '140'},
    {idparroquia: 498, nombre:'ALTAMIRA', idmunicipio: '140'},
    {idparroquia: 499, nombre:'CAPITAL ZARAZA', idmunicipio: '141'},
    {idparroquia: 500, nombre:'SAN JOSÉ DE UNARE', idmunicipio: '141'},
    {idparroquia: 501, nombre:'PÍO TAMAYO', idmunicipio: '142'},
    {idparroquia: 502, nombre:'QUEBRADA HONDA DE GUACHE', idmunicipio: '142'},
    {idparroquia: 503, nombre:'YACAMBÚ', idmunicipio: '142'},
    {idparroquia: 504, nombre:'FRÉITEZ', idmunicipio: '143'},
    {idparroquia: 505, nombre:'JOSÉ MARÍA BLANCO', idmunicipio: '143'},
    {idparroquia: 506, nombre:'CONCEPCIÓN', idmunicipio: '144'},
    {idparroquia: 507, nombre:'EL CUJÍ', idmunicipio: '144'},
    {idparroquia: 508, nombre:'JUAN DE VILLEGAS', idmunicipio: '144'},
    {idparroquia: 509, nombre:'SANTA ROSA', idmunicipio: '144'},
    {idparroquia: 510, nombre:'TAMACA', idmunicipio: '144'},
    {idparroquia: 511, nombre:'UNIÓN', idmunicipio: '144'},
    {idparroquia: 512, nombre:'AGUEDO FELIPE ALVARADO', idmunicipio: '144'},
    {idparroquia: 513, nombre:'BUENA VISTA', idmunicipio: '144'},
    {idparroquia: 514, nombre:'JUÁREZ', idmunicipio: '144'},
    {idparroquia: 515, nombre:'JUAN BAUTISTA RODRÍGUEZ', idmunicipio: '145'},
    {idparroquia: 516, nombre:'CUARA', idmunicipio: '145'},
    {idparroquia: 517, nombre:'DIEGO DE LOZADA', idmunicipio: '145'},
    {idparroquia: 518, nombre:'PARAÍSO DE SAN JOSÉ', idmunicipio: '145'},
    {idparroquia: 519, nombre:'SAN MIGUEL', idmunicipio: '145'},
    {idparroquia: 520, nombre:'TINTORERO', idmunicipio: '145'},
    {idparroquia: 521, nombre:'JOSÉ BERNARDO DORANTE', idmunicipio: '145'},
    {idparroquia: 522, nombre:'CORONEL MARIANO PERAZA', idmunicipio: '145'},
    {idparroquia: 523, nombre:'BOLÍVAR', idmunicipio: '146'},
    {idparroquia: 524, nombre:'ANZOÁTEGUI', idmunicipio: '146'},
    {idparroquia: 525, nombre:'GUARICO', idmunicipio: '146'},
    {idparroquia: 526, nombre:'HILARIO LUNA Y LUNA', idmunicipio: '146'},
    {idparroquia: 527, nombre:'HUMOCARO ALTO', idmunicipio: '146'},
    {idparroquia: 528, nombre:'HUMOCARO BAJO', idmunicipio: '146'},
    {idparroquia: 529, nombre:'LA CANDELARIA', idmunicipio: '146'},
    {idparroquia: 530, nombre:'MORÁN', idmunicipio: '146'},
    {idparroquia: 531, nombre:'CABUDARE', idmunicipio: '147'},
    {idparroquia: 532, nombre:'JOSÉ GREGORIO BASTIDAS', idmunicipio: '147'},
    {idparroquia: 533, nombre:'AGUA VIVA', idmunicipio: '147'},
    {idparroquia: 534, nombre:'SARARE', idmunicipio: '148'},
    {idparroquia: 535, nombre:'BURÍA', idmunicipio: '148'},
    {idparroquia: 536, nombre:'GUSTAVO VEGAS LEÓN', idmunicipio: '148'},
    {idparroquia: 537, nombre:'TRINIDAD SAMUEL', idmunicipio: '149'},
    {idparroquia: 538, nombre:'ANTONIO DÍAZ', idmunicipio: '149'},
    {idparroquia: 539, nombre:'CAMACARO', idmunicipio: '149'},
    {idparroquia: 540, nombre:'CASTAÑEDA', idmunicipio: '149'},
    {idparroquia: 541, nombre:'CECILIO ZUBILLAGA', idmunicipio: '149'},
    {idparroquia: 542, nombre:'CHIQUINQUIRÁ', idmunicipio: '149'},
    {idparroquia: 543, nombre:'EL BLANCO', idmunicipio: '149'},
    {idparroquia: 544, nombre:'ESPINOZA DE LOS MONTEROS', idmunicipio: '149'},
    {idparroquia: 545, nombre:'LARA', idmunicipio: '149'},
    {idparroquia: 546, nombre:'LAS MERCEDES', idmunicipio: '149'},
    {idparroquia: 547, nombre:'MANUEL MORILLO', idmunicipio: '149'},
    {idparroquia: 548, nombre:'MONTAÑA VERDE', idmunicipio: '149'},
    {idparroquia: 549, nombre:'MONTES DE OCA', idmunicipio: '149'},
    {idparroquia: 550, nombre:'TORRES', idmunicipio: '149'},
    {idparroquia: 551, nombre:'HERIBERTO ARROYO', idmunicipio: '149'},
    {idparroquia: 552, nombre:'REYES VARGAS', idmunicipio: '149'},
    {idparroquia: 553, nombre:'SIQUISIQUE', idmunicipio: '150'},
    {idparroquia: 554, nombre:'MOROTURO', idmunicipio: '150'},
    {idparroquia: 555, nombre:'SAN MIGUEL', idmunicipio: '150'},
    {idparroquia: 556, nombre:'XAGUAS', idmunicipio: '150'},
    {idparroquia: 557, nombre:'PRESIDENTE BETANCOURT', idmunicipio: '151'},
    {idparroquia: 558, nombre:'PRESIDENTE PÁEZ', idmunicipio: '151'},
    {idparroquia: 559, nombre:'PRESIDENTE RÓMULO GALLEGOS', idmunicipio: '151'},
    {idparroquia: 560, nombre:'GABRIEL PICÓN GONZÁLEZ', idmunicipio: '151'},
    {idparroquia: 561, nombre:'HÉCTOR AMABLE MORA', idmunicipio: '151'},
    {idparroquia: 562, nombre:'JOSÉ NUCETE SARDI', idmunicipio: '151'},
    {idparroquia: 563, nombre:'PULIDO MÉNDEZ', idmunicipio: '151'},
    {idparroquia: 564, nombre:'NO TIENE PARROQUIA', idmunicipio: '152'},
    {idparroquia: 565, nombre:'CAPITAL ANTONIO PINTO SALINAS', idmunicipio: '153'},
    {idparroquia: 566, nombre:'MESA BOLÍVAR', idmunicipio: '153'},
    {idparroquia: 567, nombre:'MESA DE LAS PALMAS', idmunicipio: '153'},
    {idparroquia: 568, nombre:'CAPITAL ARICAGUA', idmunicipio: '170'},
    {idparroquia: 569, nombre:'SAN ANTONIO', idmunicipio: '170'},
    {idparroquia: 570, nombre:'CAPITAL ARZOBISPO CHACÓN', idmunicipio: '171'},
    {idparroquia: 571, nombre:'CAPURÍ', idmunicipio: '171'},
    {idparroquia: 572, nombre:'CHACANTÁ', idmunicipio: '171'},
    {idparroquia: 573, nombre:'EL MOLINO', idmunicipio: '171'},
    {idparroquia: 574, nombre:'GUAIMARAL', idmunicipio: '171'},
    {idparroquia: 575, nombre:'MUCUTUY', idmunicipio: '171'},
    {idparroquia: 576, nombre:'MUCUCHACHÍ', idmunicipio: '171'},
    {idparroquia: 577, nombre:'FERNÁNDEZ PEÑA', idmunicipio: '172'},
    {idparroquia: 578, nombre:'MATRIZ', idmunicipio: '172'},
    {idparroquia: 579, nombre:'MONTALBÁN', idmunicipio: '172'},
    {idparroquia: 580, nombre:'ACEQUIAS', idmunicipio: '172'},
    {idparroquia: 581, nombre:'JAJÍ', idmunicipio: '172'},
    {idparroquia: 582, nombre:'LA MESA', idmunicipio: '172'},
    {idparroquia: 583, nombre:'SAN JOSÉ DEL SUR', idmunicipio: '172'},
    {idparroquia: 584, nombre:'CAPITAL CARACCIOLO PARRA OLMEDO', idmunicipio: '173'},
    {idparroquia: 585, nombre:'FLORENCIO RAMÍREZ EL PINAR', idmunicipio: '173'},
    {idparroquia: 586, nombre:'CAPITAL CARDENAL QUINTERO', idmunicipio: '174'},
    {idparroquia: 587, nombre:'LAS PIEDRAS', idmunicipio: '174'},
    {idparroquia: 588, nombre:'CAPITAL GUARAQUE', idmunicipio: '175'},
    {idparroquia: 589, nombre:'MESA DE QUINTERO', idmunicipio: '175'},
    {idparroquia: 590, nombre:'CATEDRAL', idmunicipio: '144'},
    {idparroquia: 591, nombre:'RÍO NEGRO', idmunicipio: '175'},
    {idparroquia: 592, nombre:'CAPITAL JULIO CÉSAR SALAS', idmunicipio: '176'},
    {idparroquia: 593, nombre:'PALMIRA', idmunicipio: '176'},
    {idparroquia: 594, nombre:'CAPITAL JUSTO BRICEÑO', idmunicipio: '177'},
    {idparroquia: 595, nombre:'SAN CRISTÓBAL DE TORONDOY', idmunicipio: '177'},
    {idparroquia: 596, nombre:'ANTONIO SPINETTI DINI', idmunicipio: '178'},
    {idparroquia: 597, nombre:'ARIAS', idmunicipio: '178'},
    {idparroquia: 598, nombre:'CARACCIOLO PARRA PÉREZ', idmunicipio: '178'},
    {idparroquia: 599, nombre:'DOMINGO PEÑA', idmunicipio: '178'},
    {idparroquia: 600, nombre:'EL LLANO', idmunicipio: '178'},
    {idparroquia: 601, nombre:'GONZALO PICÓN FEBRES', idmunicipio: '178'},
    {idparroquia: 602, nombre:'JACINTO PLAZA', idmunicipio: '178'},
    {idparroquia: 603, nombre:'JUAN RODRÍGUEZ SUÁREZ', idmunicipio: '178'},
    {idparroquia: 604, nombre:'LASSO DE LA VEGA', idmunicipio: '178'},
    {idparroquia: 605, nombre:'MARIANO PICÓN SALAS', idmunicipio: '178'},
    {idparroquia: 606, nombre:'MILLA', idmunicipio: '178'},
    {idparroquia: 607, nombre:'OSUNA RODRÍGUEZ', idmunicipio: '178'},
    {idparroquia: 608, nombre:'SAGRARIO', idmunicipio: '178'},
    {idparroquia: 609, nombre:'EL MORRO', idmunicipio: '178'},
    {idparroquia: 610, nombre:'LOS NEVADOS', idmunicipio: '178'},
    {idparroquia: 611, nombre:'CAPITAL MIRANDA', idmunicipio: '179'},
    {idparroquia: 612, nombre:'ANDRÉS ELOY BLANCO', idmunicipio: '179'},
    {idparroquia: 613, nombre:'LA VENTA', idmunicipio: '179'},
    {idparroquia: 614, nombre:'PIÑANGO', idmunicipio: '179'},
    {idparroquia: 615, nombre:'CAPITAL OBISPO RAMOS DE LORA', idmunicipio: '180'},
    {idparroquia: 616, nombre:'ELOY PAREDES', idmunicipio: '180'},
    {idparroquia: 617, nombre:'SAN RAFAEL DE ALCÁZAR', idmunicipio: '180'},
    {idparroquia: 618, nombre:'NO TIENE PARROQUIA', idmunicipio: '181'},
    {idparroquia: 619, nombre:'NO TIENE PARROQUIA', idmunicipio: '182'},
    {idparroquia: 620, nombre:'CAPITAL RANGEL', idmunicipio: '183'},
    {idparroquia: 621, nombre:'CACUTE', idmunicipio: '183'},
    {idparroquia: 622, nombre:'LA TOMA', idmunicipio: '183'},
    {idparroquia: 623, nombre:'MUCURUBÁ', idmunicipio: '183'},
    {idparroquia: 624, nombre:'SAN RAFAEL', idmunicipio: '183'},
    {idparroquia: 625, nombre:'CAPITAL RIVAS DÁVILA', idmunicipio: '184'},
    {idparroquia: 626, nombre:'GERÓNIMO MALDONADO', idmunicipio: '184'},
    {idparroquia: 627, nombre:'NO TIENE PARROQUIA', idmunicipio: '185'},
    {idparroquia: 628, nombre:'CAPITAL SUCRE', idmunicipio: '186'},
    {idparroquia: 629, nombre:'CHIGUARÁ', idmunicipio: '186'},
    {idparroquia: 630, nombre:'EL AMPARO', idmunicipio: '187'},
    {idparroquia: 631, nombre:'CAPITAL TULIO FEBRES CORDERO', idmunicipio: '188'},
    {idparroquia: 632, nombre:'CAPITAL ZEA', idmunicipio: '327'},
    {idparroquia: 633, nombre:'CAUCAGUA', idmunicipio: '189'},
    {idparroquia: 634, nombre:'ARAGÜITA', idmunicipio: '189'},
    {idparroquia: 635, nombre:'ARÉVALO GONZÁLEZ', idmunicipio: '189'},
    {idparroquia: 636, nombre:'CAPAYA', idmunicipio: '189'},
    {idparroquia: 637, nombre:'EL CAFÉ', idmunicipio: '189'},
    {idparroquia: 638, nombre:'MARIZAPA', idmunicipio: '189'},
    {idparroquia: 639, nombre:'PANAQUIRE', idmunicipio: '189'},
    {idparroquia: 640, nombre:'RIBAS', idmunicipio: '189'},
    {idparroquia: 641, nombre:'SAN JOSÉ DE BARLOVENTO', idmunicipio: '190'},
    {idparroquia: 642, nombre:'CUMBO', idmunicipio: '190'},
    {idparroquia: 643, nombre:'NUESTRA SEÑORA DEL ROSARIO DE BARUTA', idmunicipio: '191'},
    {idparroquia: 644, nombre:'EL CAFETAL', idmunicipio: '191'},
    {idparroquia: 645, nombre:'LAS MINAS DE BARUTA', idmunicipio: '191'},
    {idparroquia: 646, nombre:'HIGUEROTE', idmunicipio: '192'},
    {idparroquia: 647, nombre:'CURIEPE', idmunicipio: '192'},
    {idparroquia: 648, nombre:'TACARIGUA', idmunicipio: '192'},
    {idparroquia: 649, nombre:'MAMPORAL', idmunicipio: '193'},
    {idparroquia: 650, nombre:'CARRIZAL', idmunicipio: '194'},
    {idparroquia: 651, nombre:'CHACAO', idmunicipio: '195'},
    {idparroquia: 652, nombre:'CHARALLAVE', idmunicipio: '196'},
    {idparroquia: 653, nombre:'LAS BRISAS', idmunicipio: '196'},
    {idparroquia: 654, nombre:'EL HATILLO', idmunicipio: '197'},
    {idparroquia: 655, nombre:'LOS TEQUES', idmunicipio: '198'},
    {idparroquia: 656, nombre:'ALTAGRACIA DE LA MONTAÑA', idmunicipio: '198'},
    {idparroquia: 657, nombre:'CECILIO ACOSTA', idmunicipio: '198'},
    {idparroquia: 658, nombre:'EL JARILLO', idmunicipio: '198'},
    {idparroquia: 659, nombre:'PARACOTOS', idmunicipio: '198'},
    {idparroquia: 660, nombre:'SAN PEDRO', idmunicipio: '198'},
    {idparroquia: 661, nombre:'TÁCATA', idmunicipio: '198'},
    {idparroquia: 662, nombre:'SANTA TERESA DEL TUY', idmunicipio: '199'},
    {idparroquia: 663, nombre:'EL CARTANAL', idmunicipio: '199'},
    {idparroquia: 664, nombre:'OCUMARE DEL TUY', idmunicipio: '200'},
    {idparroquia: 665, nombre:'LA DEMOCRACIA', idmunicipio: '200'},
    {idparroquia: 666, nombre:'SANTA BÁRBARA', idmunicipio: '200'},
    {idparroquia: 667, nombre:'SAN ANTONIO DE LOS ALTOS', idmunicipio: '201'},
    {idparroquia: 668, nombre:'RÍO CHICO', idmunicipio: '202'},
    {idparroquia: 669, nombre:'EL GUAPO', idmunicipio: '202'},
    {idparroquia: 670, nombre:'TACARIGUA DE LA LAGUNA', idmunicipio: '202'},
    {idparroquia: 671, nombre:'PAPARO', idmunicipio: '202'},
    {idparroquia: 672, nombre:'SAN FERNANDO DEL GUAPO', idmunicipio: '202'},
    {idparroquia: 673, nombre:'SANTA LUCÍA', idmunicipio: '203'},
    {idparroquia: 674, nombre:'CÚPIRA', idmunicipio: '204'},
    {idparroquia: 675, nombre:'MACHURUCUTO', idmunicipio: '204'},
    {idparroquia: 676, nombre:'GUARENAS', idmunicipio: '205'},
    {idparroquia: 677, nombre:'SAN FRANCISCO DE YARE', idmunicipio: '206'},
    {idparroquia: 678, nombre:'SAN ANTONIO DE YARE', idmunicipio: '206'},
    {idparroquia: 679, nombre:'PETARE', idmunicipio: '207'},
    {idparroquia: 680, nombre:'CAUCAGÜITA', idmunicipio: '207'},
    {idparroquia: 681, nombre:'FILA DE MARICHE', idmunicipio: '207'},
    {idparroquia: 682, nombre:'LA DOLORITA', idmunicipio: '207'},
    {idparroquia: 683, nombre:'LEONCIO MARTÍNEZ', idmunicipio: '207'},
    {idparroquia: 684, nombre:'CÚA', idmunicipio: '208'},
    {idparroquia: 685, nombre:'NUEVA CÚA', idmunicipio: '208'},
    {idparroquia: 686, nombre:'GUATIRE', idmunicipio: '209'},
    {idparroquia: 687, nombre:'BOLÍVAR', idmunicipio: '209'},
    {idparroquia: 688, nombre:'NO TIENE PARROQUIA', idmunicipio: '211'},
    {idparroquia: 689, nombre:'NO TIENE PARROQUIA', idmunicipio: '212'},
    {idparroquia: 690, nombre:'CAPITAL CARIPE', idmunicipio: '213'},
    {idparroquia: 691, nombre:'EL GUÁCHARO', idmunicipio: '213'},
    {idparroquia: 692, nombre:'LA GUANOTA', idmunicipio: '213'},
    {idparroquia: 693, nombre:'SABANA DE PIEDRA', idmunicipio: '213'},
    {idparroquia: 694, nombre:'SAN AGUSTÍN', idmunicipio: '213'},
    {idparroquia: 695, nombre:'TERESÉN', idmunicipio: '213'},
    {idparroquia: 696, nombre:'CAPITAL CEDEÑO', idmunicipio: '214'},
    {idparroquia: 697, nombre:'AREO', idmunicipio: '214'},
    {idparroquia: 698, nombre:'SAN FÉLIX', idmunicipio: '214'},
    {idparroquia: 699, nombre:'VIENTO FRESCO', idmunicipio: '214'},
    {idparroquia: 700, nombre:'CAPITAL EZEQUIEL ZAMORA', idmunicipio: '215'},
    {idparroquia: 701, nombre:'EL TEJERO', idmunicipio: '215'},
    {idparroquia: 702, nombre:'CAPITAL LIBERTADOR', idmunicipio: '216'},
    {idparroquia: 703, nombre:'CHAGUARAMAS', idmunicipio: '216'},
    {idparroquia: 704, nombre:'LAS ALHUACAS', idmunicipio: '216'},
    {idparroquia: 705, nombre:'TABASCA', idmunicipio: '216'},
    {idparroquia: 706, nombre:'CAPITAL MATURÍN', idmunicipio: '217'},
    {idparroquia: 707, nombre:'ALTO DE LOS GODOS', idmunicipio: '217'},
    {idparroquia: 708, nombre:'BOQUERÓN', idmunicipio: '217'},
    {idparroquia: 709, nombre:'LAS COCUIZAS', idmunicipio: '217'},
    {idparroquia: 710, nombre:'SAN SIMÓN', idmunicipio: '217'},
    {idparroquia: 711, nombre:'SANTA CRUZ', idmunicipio: '217'},
    {idparroquia: 712, nombre:'EL COROZO', idmunicipio: '217'},
    {idparroquia: 713, nombre:'EL FURRIAL', idmunicipio: '217'},
    {idparroquia: 714, nombre:'JUSEPÍN', idmunicipio: '217'},
    {idparroquia: 715, nombre:'LA PICA', idmunicipio: '217'},
    {idparroquia: 716, nombre:'SAN VICENTE', idmunicipio: '217'},
    {idparroquia: 717, nombre:'CAPITAL PIAR', idmunicipio: '218'},
    {idparroquia: 718, nombre:'APARICIO', idmunicipio: '218'},
    {idparroquia: 719, nombre:'CHAGUARAMAL', idmunicipio: '218'},
    {idparroquia: 720, nombre:'EL PINTO', idmunicipio: '218'},
    {idparroquia: 721, nombre:'GUANAGUANA', idmunicipio: '218'},
    {idparroquia: 722, nombre:'LA TOSCANA', idmunicipio: '218'},
    {idparroquia: 723, nombre:'TAGUAYA', idmunicipio: '218'},
    {idparroquia: 724, nombre:'CAPITAL PUNCERES', idmunicipio: '219'},
    {idparroquia: 725, nombre:'CACHIPO', idmunicipio: '219'},
    {idparroquia: 726, nombre:'NO TIENE PARROQUIA', idmunicipio: '220'},
    {idparroquia: 727, nombre:'CAPITAL SOTILLO', idmunicipio: '221'},
    {idparroquia: 728, nombre:'LOS BARRANCOS DE FAJARDO', idmunicipio: '221'},
    {idparroquia: 729, nombre:'NO TIENE PARROQUIA', idmunicipio: '222'},
    {idparroquia: 730, nombre:'NO TIENE PARROQUIA', idmunicipio: '223'},
    {idparroquia: 731, nombre:'NO TIENE PARROQUIA', idmunicipio: '224'},
    {idparroquia: 732, nombre:'CAPITAL DÍAZ', idmunicipio: '225'},
    {idparroquia: 733, nombre:'CAPITAL GARCÍA', idmunicipio: '226'},
    {idparroquia: 734, nombre:'FRANCISCO FAJARDO', idmunicipio: '226'},
    {idparroquia: 735, nombre:'CAPITAL GÓMEZ', idmunicipio: '227'},
    {idparroquia: 736, nombre:'BOLÍVAR', idmunicipio: '227'},
    {idparroquia: 737, nombre:'GUEVARA', idmunicipio: '227'},
    {idparroquia: 738, nombre:'MATASIETE', idmunicipio: '227'},
    {idparroquia: 739, nombre:'SUCRE', idmunicipio: '227'},
    {idparroquia: 740, nombre:'CAPITAL MANEIRO', idmunicipio: '228'},
    {idparroquia: 741, nombre:'AGUIRRE', idmunicipio: '228'},
    {idparroquia: 742, nombre:'CAPITAL MARCANO', idmunicipio: '229'},
    {idparroquia: 743, nombre:'ADRIÁN', idmunicipio: '229'},
    {idparroquia: 744, nombre:'NO TIENE PARROQUIA', idmunicipio: '230'},
    {idparroquia: 745, nombre:'CAPITAL PENÍNSULA DE MACANAO', idmunicipio: '231'},
    {idparroquia: 746, nombre:'SAN FRANCISCO', idmunicipio: '231'},
    {idparroquia: 747, nombre:'CAPITAL TUBORES', idmunicipio: '232'},
    {idparroquia: 748, nombre:'LOS BARALES', idmunicipio: '232'},
    {idparroquia: 749, nombre:'CAPITAL VILLALBA', idmunicipio: '233'},
    {idparroquia: 750, nombre:'NO TIENE PARROQUIA', idmunicipio: '234'},
    {idparroquia: 751, nombre:'CAPITAL ARAURE', idmunicipio: '235'},
    {idparroquia: 752, nombre:'RÍO ACARIGUA', idmunicipio: '235'},
    {idparroquia: 753, nombre:'CAPITAL ESTELLER', idmunicipio: '236'},
    {idparroquia: 754, nombre:'UVERAL', idmunicipio: '236'},
    {idparroquia: 755, nombre:'CAPITAL GUANARE', idmunicipio: '237'},
    {idparroquia: 756, nombre:'CÓRDOBA', idmunicipio: '237'},
    {idparroquia: 757, nombre:'SAN JOSÉ DE LA MONTAÑA', idmunicipio: '237'},
    {idparroquia: 758, nombre:'SAN JUAN DE GUANAGUANARE', idmunicipio: '237'},
    {idparroquia: 759, nombre:'VIRGEN DE LA COROMOTO', idmunicipio: '237'},
    {idparroquia: 760, nombre:'CAPITAL GUANARITO', idmunicipio: '238'},
    {idparroquia: 761, nombre:'TRINIDAD DE LA CAPILLA', idmunicipio: '238'},
    {idparroquia: 762, nombre:'DIVINA PASTORA', idmunicipio: '238'},
    {idparroquia: 763, nombre:'CAPITAL MONS. JOSÉ VICENTE DE UNDA', idmunicipio: '239'},
    {idparroquia: 764, nombre:'PEÑA BLANCA', idmunicipio: '239'},
    {idparroquia: 765, nombre:'CAPITAL OSPINO', idmunicipio: '240'},
    {idparroquia: 766, nombre:'APARICIÓN', idmunicipio: '240'},
    {idparroquia: 767, nombre:'LA ESTACIÓN', idmunicipio: '240'},
    {idparroquia: 768, nombre:'CAPITAL PÁEZ', idmunicipio: '242'},
    {idparroquia: 769, nombre:'PAYARA', idmunicipio: '242'},
    {idparroquia: 770, nombre:'PIMPINELA', idmunicipio: '242'},
    {idparroquia: 771, nombre:'RAMÓN PERAZA', idmunicipio: '242'},
    {idparroquia: 772, nombre:'CAPITAL PAPELÓN', idmunicipio: '243'},
    {idparroquia: 773, nombre:'CAÑO DELGADITO', idmunicipio: '243'},
    {idparroquia: 774, nombre:'CAPITAL SAN GENARO DE BOCONOITO', idmunicipio: '244'},
    {idparroquia: 775, nombre:'ANTOLÍN TOVAR', idmunicipio: '244'},
    {idparroquia: 776, nombre:'CAPITAL SAN RAFAEL DE ONOTO', idmunicipio: '245'},
    {idparroquia: 777, nombre:'SANTA FE', idmunicipio: '245'},
    {idparroquia: 778, nombre:'THERMO MORLES', idmunicipio: '245'},
    {idparroquia: 779, nombre:'CAPITAL SANTA ROSALÍA', idmunicipio: '246'},
    {idparroquia: 780, nombre:'FLORIDA', idmunicipio: '246'},
    {idparroquia: 781, nombre:'CAPITAL SUCRE', idmunicipio: '247'},
    {idparroquia: 782, nombre:'CONCEPCIÓN', idmunicipio: '247'},
    {idparroquia: 783, nombre:'SAN RAFAEL DE PALO ALZADO', idmunicipio: '247'},
    {idparroquia: 784, nombre:'UVENCIO ANTONIO VELÁSQUEZ', idmunicipio: '247'},
    {idparroquia: 785, nombre:'SAN JOSÉ DE SAGUAZ', idmunicipio: '247'},
    {idparroquia: 786, nombre:'VILLA ROSA', idmunicipio: '247'},
    {idparroquia: 787, nombre:'CAPITAL TURÉN', idmunicipio: '248'},
    {idparroquia: 788, nombre:'CANELONES', idmunicipio: '248'},
    {idparroquia: 789, nombre:'SANTA CRUZ', idmunicipio: '248'},
    {idparroquia: 790, nombre:'SAN ISIDRO LABRADOR', idmunicipio: '248'},
    {idparroquia: 791, nombre:'MARIÑO', idmunicipio: '249'},
    {idparroquia: 792, nombre:'RÓMULO GALLEGOS', idmunicipio: '249'},
    {idparroquia: 793, nombre:'SAN JOSÉ DE AEROCUAR', idmunicipio: '250'},
    {idparroquia: 794, nombre:'TAVERA ACOSTA', idmunicipio: '250'},
    {idparroquia: 795, nombre:'RÍO CARIBE', idmunicipio: '251'},
    {idparroquia: 796, nombre:'ANTONIO JOSÉ DE SUCRE', idmunicipio: '251'},
    {idparroquia: 797, nombre:'EL MORRO DE PUERTO SANTO', idmunicipio: '251'},
    {idparroquia: 798, nombre:'PUERTO SANTO', idmunicipio: '251'},
    {idparroquia: 799, nombre:'SAN JUAN DE LAS GALDONAS', idmunicipio: '251'},
    {idparroquia: 800, nombre:'EL PILAR', idmunicipio: '252'},
    {idparroquia: 801, nombre:'EL RINCÓN', idmunicipio: '252'},
    {idparroquia: 802, nombre:'GENERAL FRANCISCO ANTONIO VÁSQUEZ', idmunicipio: '252'},
    {idparroquia: 803, nombre:'GUARAÚNOS', idmunicipio: '252'},
    {idparroquia: 804, nombre:'TUNAPUICITO', idmunicipio: '252'},
    {idparroquia: 805, nombre:'UNIÓN', idmunicipio: '252'},
    {idparroquia: 806, nombre:'BOLÍVAR', idmunicipio: '253'},
    {idparroquia: 807, nombre:'MACARAPANA', idmunicipio: '253'},
    {idparroquia: 808, nombre:'SANTA CATALINA', idmunicipio: '253'},
    {idparroquia: 809, nombre:'SANTA ROSA', idmunicipio: '253'},
    {idparroquia: 810, nombre:'SANTA TERESA', idmunicipio: '253'},
    {idparroquia: 811, nombre:'NO TIENE PARROQUIA', idmunicipio: '254'},
    {idparroquia: 812, nombre:'YAGUARAPARO', idmunicipio: '128'},
    {idparroquia: 813, nombre:'EL PAUJIL', idmunicipio: '128'},
    {idparroquia: 814, nombre:'LIBERTAD', idmunicipio: '128'},
    {idparroquia: 815, nombre:'ARAYA', idmunicipio: '255'},
    {idparroquia: 816, nombre:'CHACOPATA', idmunicipio: '255'},
    {idparroquia: 817, nombre:'MANICUARE', idmunicipio: '255'},
    {idparroquia: 818, nombre:'TUNAPUY', idmunicipio: '256'},
    {idparroquia: 819, nombre:'CAMPO ELÍAS', idmunicipio: '256'},
    {idparroquia: 820, nombre:'IRAPA', idmunicipio: '257'},
    {idparroquia: 821, nombre:'CAMPO CLARO', idmunicipio: '257'},
    {idparroquia: 822, nombre:'MARABAL', idmunicipio: '257'},
    {idparroquia: 823, nombre:'SAN ANTONIO DE IRAPA', idmunicipio: '257'},
    {idparroquia: 824, nombre:'SORO', idmunicipio: '257'},
    {idparroquia: 825, nombre:'NO TIENE PARROQUIA', idmunicipio: '258'},
    {idparroquia: 826, nombre:'CUMANACOA', idmunicipio: '259'},
    {idparroquia: 827, nombre:'ARENAS', idmunicipio: '259'},
    {idparroquia: 828, nombre:'ARICAGUA', idmunicipio: '259'},
    {idparroquia: 829, nombre:'COCOLLAR', idmunicipio: '259'},
    {idparroquia: 830, nombre:'SAN FERNANDO', idmunicipio: '259'},
    {idparroquia: 831, nombre:'SAN LORENZO', idmunicipio: '259'},
    {idparroquia: 832, nombre:'CATUARO', idmunicipio: '260'},
    {idparroquia: 833, nombre:'RENDÓN VILLA FRONTADO', idmunicipio: '260'},
    {idparroquia: 834, nombre:'SANTA CRUZ', idmunicipio: '260'},
    {idparroquia: 835, nombre:'SANTA MARÍA', idmunicipio: '260'},
    {idparroquia: 836, nombre:'AYACUCHO', idmunicipio: '261'},
    {idparroquia: 837, nombre:'SANTA INÉS', idmunicipio: '261'},
    {idparroquia: 838, nombre:'VALENTÍN VALIENTE', idmunicipio: '261'},
    {idparroquia: 839, nombre:'SAN JUAN', idmunicipio: '261'},
    {idparroquia: 840, nombre:'RAÚL LEONI', idmunicipio: '261'},
    {idparroquia: 841, nombre:'GRAN MARISCAL', idmunicipio: '261'},
    {idparroquia: 842, nombre:'GÜIRIA', idmunicipio: '262'},
    {idparroquia: 843, nombre:'CRISTÓBAL COLÓN', idmunicipio: '262'},
    {idparroquia: 844, nombre:'PUNTA DE PIEDRAS', idmunicipio: '262'},
    {idparroquia: 845, nombre:'NO TIENE PARROQUIA', idmunicipio: '263'},
    {idparroquia: 846, nombre:'NO TIENE PARROQUIA', idmunicipio: '264'},
    {idparroquia: 847, nombre:'AYACUCHO', idmunicipio: '265'},
    {idparroquia: 848, nombre:'RIVAS BERTI', idmunicipio: '265'},
    {idparroquia: 849, nombre:'SAN PEDRO DEL RÍO', idmunicipio: '265'},
    {idparroquia: 850, nombre:'BOLÍVAR', idmunicipio: '266'},
    {idparroquia: 851, nombre:'PALOTAL', idmunicipio: '266'},
    {idparroquia: 852, nombre:'JUAN VICENTE GÓMEZ', idmunicipio: '266'},
    {idparroquia: 853, nombre:'ISAÍAS MEDINA ANGARITA', idmunicipio: '266'},
    {idparroquia: 854, nombre:'CÁRDENAS', idmunicipio: '267'},
    {idparroquia: 855, nombre:'AMENODORO RANGEL LAMÚS', idmunicipio: '267'},
    {idparroquia: 856, nombre:'LA FLORIDA', idmunicipio: '267'},
    {idparroquia: 857, nombre:'NO TIENE PARROQUIA', idmunicipio: '268'},
    {idparroquia: 858, nombre:'FERNÁNDEZ FEO', idmunicipio: '269'},
    {idparroquia: 859, nombre:'ALBERTO ADRIANI', idmunicipio: '269'},
    {idparroquia: 860, nombre:'SANTO DOMINGO', idmunicipio: '269'},
    {idparroquia: 861, nombre:'ALTAGRACIA', idmunicipio: '261'},
    {idparroquia: 862, nombre:'GARCÍA DE HEVIA', idmunicipio: '271'},
    {idparroquia: 863, nombre:'BOCA DE GRITA', idmunicipio: '271'},
    {idparroquia: 864, nombre:'JOSÉ ANTONIO PÁEZ', idmunicipio: '271'},
    {idparroquia: 865, nombre:'NO TIENE PARROQUIA', idmunicipio: '272'},
    {idparroquia: 866, nombre:'INDEPENDENCIA', idmunicipio: '273'},
    {idparroquia: 867, nombre:'JUAN GERMÁN ROSCIO', idmunicipio: '273'},
    {idparroquia: 868, nombre:'ROMÁN CÁRDENAS', idmunicipio: '273'},
    {idparroquia: 869, nombre:'JÁUREGUI', idmunicipio: '274'},
    {idparroquia: 870, nombre:'EMILIO CONSTANTINO GUERRERO', idmunicipio: '274'},
    {idparroquia: 871, nombre:'MONSEÑOR MIGUEL ANTONIO SALAS', idmunicipio: '274'},
    {idparroquia: 872, nombre:'NO TIENE PARROQUIA', idmunicipio: '275'},
    {idparroquia: 873, nombre:'JUNÍN', idmunicipio: '276'},
    {idparroquia: 874, nombre:'LA PETRÓLEA', idmunicipio: '276'},
    {idparroquia: 875, nombre:'QUINIMARÍ', idmunicipio: '276'},
    {idparroquia: 876, nombre:'BRAMÓN', idmunicipio: '276'},
    {idparroquia: 877, nombre:'LIBERTAD', idmunicipio: '277'},
    {idparroquia: 878, nombre:'CIPRIANO CASTRO', idmunicipio: '277'},
    {idparroquia: 879, nombre:'MANUEL FELIPE RUGELES', idmunicipio: '277'},
    {idparroquia: 880, nombre:'LIBERTADOR', idmunicipio: '278'},
    {idparroquia: 881, nombre:'DON EMETERIO OCHOA', idmunicipio: '278'},
    {idparroquia: 882, nombre:'DORADAS', idmunicipio: '278'},
    {idparroquia: 883, nombre:'SAN JOAQUÍN DE NAVAY', idmunicipio: '278'},
    {idparroquia: 884, nombre:'LOBATERA', idmunicipio: '279'},
    {idparroquia: 885, nombre:'CONSTITUCIÓN', idmunicipio: '279'},
    {idparroquia: 886, nombre:'NO TIENE PARROQUIA', idmunicipio: '280'},
    {idparroquia: 887, nombre:'PANAMERICANO', idmunicipio: '281'},
    {idparroquia: 888, nombre:'LA PALMITA', idmunicipio: '281'},
    {idparroquia: 889, nombre:'PEDRO MARÍA UREÑA', idmunicipio: '282'},
    {idparroquia: 890, nombre:'NUEVA ARCADIA', idmunicipio: '282'},
    {idparroquia: 891, nombre:'NO TIENE PARROQUIA', idmunicipio: '283'},
    {idparroquia: 892, nombre:'SAMUEL DARÍO MALDONADO', idmunicipio: '284'},
    {idparroquia: 893, nombre:'BOCONÓ', idmunicipio: '284'},
    {idparroquia: 894, nombre:'HERNÁNDEZ', idmunicipio: '284'},
    {idparroquia: 895, nombre:'LA CONCORDIA', idmunicipio: '285'},
    {idparroquia: 896, nombre:'PEDRO MARÍA MORANTES', idmunicipio: '285'},
    {idparroquia: 897, nombre:'SAN JUAN BAUTISTA', idmunicipio: '285'},
    {idparroquia: 898, nombre:'SAN SEBASTIÁN', idmunicipio: '285'},
    {idparroquia: 899, nombre:'DR. FRANCISCO ROMERO', idmunicipio: '285'},
    {idparroquia: 900, nombre:'NO TIENE PARROQUIA', idmunicipio: '286'},
    {idparroquia: 901, nombre:'NO TIENE PARROQUIA', idmunicipio: '287'},
    {idparroquia: 902, nombre:'SUCRE', idmunicipio: '288'},
    {idparroquia: 903, nombre:'ELEAZAR LÓPEZ CONTRERAS', idmunicipio: '288'},
    {idparroquia: 904, nombre:'SAN PABLO', idmunicipio: '288'},
    {idparroquia: 905, nombre:'NO TIENE PARROQUIA', idmunicipio: '289'},
    {idparroquia: 906, nombre:'URIBANTE', idmunicipio: '290'},
    {idparroquia: 907, nombre:'CÁRDENAS', idmunicipio: '290'},
    {idparroquia: 908, nombre:'JUAN PABLO PEÑALOZA', idmunicipio: '290'},
    {idparroquia: 909, nombre:'POTOSÍ', idmunicipio: '290'},
    {idparroquia: 910, nombre:'NO TIENE PARROQUIA', idmunicipio: '291'},
    {idparroquia: 911, nombre:'SANTA ISABEL', idmunicipio: '292'},
    {idparroquia: 912, nombre:'ARAGUANEY', idmunicipio: '292'},
    {idparroquia: 913, nombre:'EL JAGÜITO', idmunicipio: '292'},
    {idparroquia: 914, nombre:'LA ESPERANZA', idmunicipio: '292'},
    {idparroquia: 915, nombre:'BOCONÓ', idmunicipio: '293'},
    {idparroquia: 916, nombre:'EL CARMEN', idmunicipio: '293'},
    {idparroquia: 917, nombre:'MOSQUEY', idmunicipio: '293'},
    {idparroquia: 918, nombre:'AYACUCHO', idmunicipio: '293'},
    {idparroquia: 919, nombre:'BURBUSAY', idmunicipio: '293'},
    {idparroquia: 920, nombre:'GENERAL RIVAS', idmunicipio: '293'},
    {idparroquia: 921, nombre:'GUARAMACAL', idmunicipio: '293'},
    {idparroquia: 922, nombre:'VEGA DE GUARAMACAL', idmunicipio: '293'},
    {idparroquia: 923, nombre:'MONSEÑOR JÁUREGUI', idmunicipio: '293'},
    {idparroquia: 924, nombre:'RAFAEL RANGEL', idmunicipio: '293'},
    {idparroquia: 925, nombre:'SAN MIGUEL', idmunicipio: '293'},
    {idparroquia: 926, nombre:'SAN JOSÉ', idmunicipio: '293'},
    {idparroquia: 927, nombre:'SABANA GRANDE', idmunicipio: '294'},
    {idparroquia: 928, nombre:'CHEREGÜÉ', idmunicipio: '294'},
    {idparroquia: 929, nombre:'GRANADOS', idmunicipio: '294'},
    {idparroquia: 930, nombre:'CHEJENDÉ', idmunicipio: '295'},
    {idparroquia: 931, nombre:'ARNOLDO GABALDÓN', idmunicipio: '295'},
    {idparroquia: 932, nombre:'BOLIVIA', idmunicipio: '295'},
    {idparroquia: 933, nombre:'CARRILLO', idmunicipio: '295'},
    {idparroquia: 934, nombre:'CEGARRA', idmunicipio: '295'},
    {idparroquia: 935, nombre:'MANUEL SALVADOR ULLOA', idmunicipio: '295'},
    {idparroquia: 936, nombre:'SAN JOSÉ', idmunicipio: '295'},
    {idparroquia: 937, nombre:'CARACHE', idmunicipio: '296'},
    {idparroquia: 938, nombre:'CUICAS', idmunicipio: '296'},
    {idparroquia: 939, nombre:'LA CONCEPCIÓN', idmunicipio: '296'},
    {idparroquia: 940, nombre:'PANAMERICANA', idmunicipio: '296'},
    {idparroquia: 941, nombre:'SANTA CRUZ', idmunicipio: '296'},
    {idparroquia: 942, nombre:'ESCUQUE', idmunicipio: '297'},
    {idparroquia: 943, nombre:'LA UNIÓN', idmunicipio: '297'},
    {idparroquia: 944, nombre:'SABANA LIBRE', idmunicipio: '297'},
    {idparroquia: 945, nombre:'SANTA RITA', idmunicipio: '297'},
    {idparroquia: 946, nombre:'EL SOCORRO', idmunicipio: '298'},
    {idparroquia: 947, nombre:'ANTONIO JOSÉ DE SUCRE', idmunicipio: '298'},
    {idparroquia: 948, nombre:'LOS CAPRICHOS', idmunicipio: '298'},
    {idparroquia: 949, nombre:'CAMPO ELÍAS', idmunicipio: '299'},
    {idparroquia: 950, nombre:'ARNOLDO GABALDÓN', idmunicipio: '299'},
    {idparroquia: 951, nombre:'SANTA APOLONIA', idmunicipio: '300'},
    {idparroquia: 952, nombre:'EL PROGRESO', idmunicipio: '300'},
    {idparroquia: 953, nombre:'LA CEIBA', idmunicipio: '300'},
    {idparroquia: 954, nombre:'TRES DE FEBRERO', idmunicipio: '300'},
    {idparroquia: 955, nombre:'EL DIVIDIVE', idmunicipio: '301'},
    {idparroquia: 956, nombre:'AGUA SANTA', idmunicipio: '301'},
    {idparroquia: 957, nombre:'AGUA CALIENTE', idmunicipio: '301'},
    {idparroquia: 958, nombre:'EL CENIZO', idmunicipio: '301'},
    {idparroquia: 959, nombre:'VALERITA', idmunicipio: '301'},
    {idparroquia: 960, nombre:'MONTE CARMELO', idmunicipio: '302'},
    {idparroquia: 961, nombre:'BUENA VISTA', idmunicipio: '302'},
    {idparroquia: 962, nombre:'SANTA MARÍA DEL HORCÓN', idmunicipio: '302'},
    {idparroquia: 963, nombre:'MOTATÁN', idmunicipio: '303'},
    {idparroquia: 964, nombre:'EL BAÑO', idmunicipio: '303'},
    {idparroquia: 965, nombre:'JALISCO', idmunicipio: '303'},
    {idparroquia: 966, nombre:'PAMPÁN', idmunicipio: '304'},
    {idparroquia: 967, nombre:'FLOR DE PATRIA', idmunicipio: '304'},
    {idparroquia: 968, nombre:'LA PAZ', idmunicipio: '304'},
    {idparroquia: 969, nombre:'SANTA ANA', idmunicipio: '304'},
    {idparroquia: 970, nombre:'PAMPANITO', idmunicipio: '305'},
    {idparroquia: 971, nombre:'LA CONCEPCIÓN', idmunicipio: '305'},
    {idparroquia: 972, nombre:'PAMPANITO II', idmunicipio: '305'},
    {idparroquia: 973, nombre:'BETIJOQUE', idmunicipio: '306'},
    {idparroquia: 974, nombre:'LA PUEBLITA', idmunicipio: '306'},
    {idparroquia: 975, nombre:'LOS CEDROS', idmunicipio: '306'},
    {idparroquia: 976, nombre:'JOSÉ GREGORIO HERNÁNDEZ', idmunicipio: '306'},
    {idparroquia: 977, nombre:'CARVAJAL', idmunicipio: '307'},
    {idparroquia: 978, nombre:'ANTONIO NICOLÁS BRICEÑO', idmunicipio: '307'},
    {idparroquia: 979, nombre:'CAMPO ALEGRE', idmunicipio: '307'},
    {idparroquia: 980, nombre:'JOSÉ LEONARDO SUÁREZ', idmunicipio: '307'},
    {idparroquia: 981, nombre:'SABANA DE MENDOZA', idmunicipio: '308'},
    {idparroquia: 982, nombre:'VALMORE RODRÍGUEZ', idmunicipio: '308'},
    {idparroquia: 983, nombre:'ANDRÉS LINARES', idmunicipio: '309'},
    {idparroquia: 984, nombre:'CHIQUINQUIRÁ', idmunicipio: '309'},
    {idparroquia: 985, nombre:'CRISTÓBAL MENDOZA', idmunicipio: '309'},
    {idparroquia: 986, nombre:'CRUZ CARRILLO', idmunicipio: '309'},
    {idparroquia: 987, nombre:'MATRIZ', idmunicipio: '309'},
    {idparroquia: 988, nombre:'MONSEÑOR CARRILLO', idmunicipio: '309'},
    {idparroquia: 989, nombre:'TRES ESQUINAS', idmunicipio: '309'},
    {idparroquia: 990, nombre:'LA QUEBRADA', idmunicipio: '310'},
    {idparroquia: 991, nombre:'CABIMBÚ', idmunicipio: '310'},
    {idparroquia: 992, nombre:'JAJÓ', idmunicipio: '310'},
    {idparroquia: 993, nombre:'LA MESA', idmunicipio: '310'},
    {idparroquia: 994, nombre:'SANTIAGO', idmunicipio: '310'},
    {idparroquia: 995, nombre:'TUÑAME', idmunicipio: '310'},
    {idparroquia: 996, nombre:'JUAN IGNACIO MONTILLA', idmunicipio: '311'},
    {idparroquia: 997, nombre:'LA BEATRIZ', idmunicipio: '311'},
    {idparroquia: 998, nombre:'MERCEDES DÍAZ', idmunicipio: '311'},
    {idparroquia: 999, nombre:'SAN LUIS', idmunicipio: '311'},
    {idparroquia: 1000, nombre:'LA PUERTA', idmunicipio: '311'},
    {idparroquia: 1001, nombre:'MENDOZA', idmunicipio: '311'},
    {idparroquia: 1002, nombre:'NO TIENE PARROQUIA', idmunicipio: '312'},
    {idparroquia: 1003, nombre:'NO TIENE PARROQUIA', idmunicipio: '313'},
    {idparroquia: 1004, nombre:'CAPITAL BRUZUAL 2/ CHIVACOA', idmunicipio: '314'},
    {idparroquia: 1005, nombre:'NO TIENE PARROQUIA', idmunicipio: '315'},
    {idparroquia: 1006, nombre:'NO TIENE PARROQUIA', idmunicipio: '316'},
    {idparroquia: 1007, nombre:'CAMPO ELÍAS', idmunicipio: '314'},
    {idparroquia: 1008, nombre:'NO TIENE PARROQUIA', idmunicipio: '317'},
    {idparroquia: 1009, nombre:'NO TIENE PARROQUIA', idmunicipio: '318'},
    {idparroquia: 1010, nombre:'CAPITAL NIRGUA', idmunicipio: '320'},
    {idparroquia: 1011, nombre:'TEMERLA', idmunicipio: '320'},
    {idparroquia: 1012, nombre:'CAPITAL PEÑA', idmunicipio: '321'},
    {idparroquia: 1013, nombre:'SAN ANDRÉS', idmunicipio: '321'},
    {idparroquia: 1014, nombre:'CAPITAL SAN FELIPE', idmunicipio: '322'},
    {idparroquia: 1015, nombre:'ALBARICO', idmunicipio: '322'},
    {idparroquia: 1016, nombre:'SAN JAVIER', idmunicipio: '322'},
    {idparroquia: 1017, nombre:'NO TIENE PARROQUIA', idmunicipio: '323'},
    {idparroquia: 1018, nombre:'NO TIENE PARROQUIA', idmunicipio: '324'},
    {idparroquia: 1019, nombre:'CAPITAL VEROES', idmunicipio: '325'},
    {idparroquia: 1020, nombre:'EL GUAYABO', idmunicipio: '325'},
    {idparroquia: 1021, nombre:'ISLA DE TOAS', idmunicipio: '326'},
    {idparroquia: 1022, nombre:'MONAGAS', idmunicipio: '326'},
    {idparroquia: 1023, nombre:'SAN TIMOTEO', idmunicipio: '132'},
    {idparroquia: 1024, nombre:'GENERAL URDANETA', idmunicipio: '132'},
    {idparroquia: 1025, nombre:'LIBERTADOR', idmunicipio: '132'},
    {idparroquia: 1026, nombre:'MANUEL GUANIPA MATOS', idmunicipio: '132'},
    {idparroquia: 1027, nombre:'MARCELINO BRICEÑO', idmunicipio: '132'},
    {idparroquia: 1028, nombre:'PUEBLO NUEVO', idmunicipio: '132'},
    {idparroquia: 1029, nombre:'AMBROSIO', idmunicipio: '59'},
    {idparroquia: 1030, nombre:'CARMEN HERRERA', idmunicipio: '59'},
    {idparroquia: 1031, nombre:'GERMÁN RÍOS LINARES', idmunicipio: '59'},
    {idparroquia: 1032, nombre:'LA ROSA', idmunicipio: '59'},
    {idparroquia: 1033, nombre:'JORGE HERNÁNDEZ', idmunicipio: '59'},
    {idparroquia: 1034, nombre:'RÓMULO BETANCOURT', idmunicipio: '59'},
    {idparroquia: 1035, nombre:'SAN BENITO', idmunicipio: '59'},
    {idparroquia: 1036, nombre:'ARÍSTIDES CALVANI', idmunicipio: '59'},
    {idparroquia: 1037, nombre:'PUNTA GORDA', idmunicipio: '59'},
    {idparroquia: 1038, nombre:'ENCONTRADOS', idmunicipio: '60'},
    {idparroquia: 1039, nombre:'UDÓN PÉREZ', idmunicipio: '60'},
    {idparroquia: 1040, nombre:'SAN CARLOS DEL ZULIA', idmunicipio: '61'},
    {idparroquia: 1041, nombre:'MORALITO', idmunicipio: '61'},
    {idparroquia: 1042, nombre:'SANTA BÁRBARA', idmunicipio: '61'},
    {idparroquia: 1043, nombre:'SANTA CRUZ DEL ZULIA', idmunicipio: '61'},
    {idparroquia: 1044, nombre:'URRIBARRI', idmunicipio: '61'},
    {idparroquia: 1045, nombre:'SIMÓN RODRÍGUEZ', idmunicipio: '62'},
    {idparroquia: 1046, nombre:'CARLOS QUEVEDO', idmunicipio: '62'},
    {idparroquia: 1047, nombre:'FRANCISCO JAVIER PULGAR', idmunicipio: '62'},
    {idparroquia: 1048, nombre:'LA CONCEPCIÓN', idmunicipio: '63'},
    {idparroquia: 1049, nombre:'JOSÉ RAMÓN YEPES', idmunicipio: '63'},
    {idparroquia: 1050, nombre:'MARIANO PARRA LEÓN', idmunicipio: '63'},
    {idparroquia: 1051, nombre:'SAN JOSÉ', idmunicipio: '63'},
    {idparroquia: 1052, nombre:'JESÚS MARÍA SEMPRÚN', idmunicipio: '64'},
    {idparroquia: 1053, nombre:'BARÍ', idmunicipio: '64'},
    {idparroquia: 1054, nombre:'CONCEPCIÓN', idmunicipio: '65'},
    {idparroquia: 1055, nombre:'ANDRÉS BELLO', idmunicipio: '65'},
    {idparroquia: 1056, nombre:'CHIQUINQUIRÁ', idmunicipio: '65'},
    {idparroquia: 1057, nombre:'EL CARMELO', idmunicipio: '65'},
    {idparroquia: 1058, nombre:'POTRERITOS', idmunicipio: '65'},
    {idparroquia: 1059, nombre:'ALONSO DE OJEDA', idmunicipio: '66'},
    {idparroquia: 1060, nombre:'LIBERTAD', idmunicipio: '66'},
    {idparroquia: 1061, nombre:'CAMPO LARA', idmunicipio: '66'},
    {idparroquia: 1062, nombre:'ELEAZAR LÓPEZ CONTRERAS', idmunicipio: '66'},
    {idparroquia: 1063, nombre:'VENEZUELA', idmunicipio: '66'},
    {idparroquia: 1064, nombre:'LIBERTAD', idmunicipio: '67'},
    {idparroquia: 1065, nombre:'BARTOLOMÉ DE LAS CASAS', idmunicipio: '67'},
    {idparroquia: 1066, nombre:'RÍO NEGRO', idmunicipio: '67'},
    {idparroquia: 1067, nombre:'SAN JOSÉ DE PERIJÁ', idmunicipio: '67'},
    {idparroquia: 1068, nombre:'SAN RAFAEL', idmunicipio: '68'},
    {idparroquia: 1069, nombre:'LA SIERRITA', idmunicipio: '68'},
    {idparroquia: 1070, nombre:'LAS PARCELAS', idmunicipio: '68'},
    {idparroquia: 1071, nombre:'LUIS DE VICENTE', idmunicipio: '68'},
    {idparroquia: 1072, nombre:'MONSEÑOR MARCOS SERGIO GODOY', idmunicipio: '68'},
    {idparroquia: 1073, nombre:'RICAURTE', idmunicipio: '68'},
    {idparroquia: 1074, nombre:'TAMARE', idmunicipio: '68'},
    {idparroquia: 1075, nombre:'ANTONIO BORJAS ROMERO', idmunicipio: '69'},
    {idparroquia: 1076, nombre:'BOLÍVAR', idmunicipio: '69'},
    {idparroquia: 1077, nombre:'CACIQUE MARA', idmunicipio: '69'},
    {idparroquia: 1078, nombre:'CARACCIOLO PARRA PÉREZ', idmunicipio: '69'},
    {idparroquia: 1079, nombre:'CECILIO ACOSTA', idmunicipio: '69'},
    {idparroquia: 1080, nombre:'CRISTO DE ARANZA', idmunicipio: '69'},
    {idparroquia: 1081, nombre:'COQUIVACOA', idmunicipio: '69'},
    {idparroquia: 1082, nombre:'CHIQUINQUIRÁ', idmunicipio: '69'},
    {idparroquia: 1083, nombre:'FRANCISCO EUGENIO BUSTAMANTE', idmunicipio: '69'},
    {idparroquia: 1084, nombre:'IDELFONSO VÁSQUEZ', idmunicipio: '69'},
    {idparroquia: 1085, nombre:'JUANA DE ÁVILA', idmunicipio: '69'},
    {idparroquia: 1086, nombre:'LUIS HURTADO HIGUERA', idmunicipio: '69'},
    {idparroquia: 1087, nombre:'MANUEL DAGNINO', idmunicipio: '69'},
    {idparroquia: 1088, nombre:'OLEGARIO VILLALOBOS', idmunicipio: '69'},
    {idparroquia: 1089, nombre:'RAÚL LEONI', idmunicipio: '69'},
    {idparroquia: 1090, nombre:'SANTA LUCÍA', idmunicipio: '69'},
    {idparroquia: 1091, nombre:'VENANCIO PULGAR', idmunicipio: '69'},
    {idparroquia: 1092, nombre:'SAN ISIDRO', idmunicipio: '69'},
    {idparroquia: 1093, nombre:'ANA MARÍA CAMPOS', idmunicipio: '70'},
    {idparroquia: 1094, nombre:'FARÍA', idmunicipio: '70'},
    {idparroquia: 1095, nombre:'SAN ANTONIO', idmunicipio: '70'},
    {idparroquia: 1096, nombre:'SAN JOSÉ', idmunicipio: '70'},
    {idparroquia: 1097, nombre:'SINAMAICA', idmunicipio: '71'},
    {idparroquia: 1098, nombre:'ALTA GUAJIRA', idmunicipio: '71'},
    {idparroquia: 1099, nombre:'ELÍAS SÁNCHEZ RUBIO', idmunicipio: '71'},
    {idparroquia: 1100, nombre:'GUAJIRA', idmunicipio: '71'},
    {idparroquia: 1101, nombre:'EL ROSARIO', idmunicipio: '72'},
    {idparroquia: 1102, nombre:'DONALDO GARCÍA', idmunicipio: '72'},
    {idparroquia: 1103, nombre:'SIXTO ZAMBRANO', idmunicipio: '72'},
    {idparroquia: 1104, nombre:'SAN FRANCISCO', idmunicipio: '73'},
    {idparroquia: 1105, nombre:'EL BAJO', idmunicipio: '73'},
    {idparroquia: 1106, nombre:'DOMITILA FLORES', idmunicipio: '73'},
    {idparroquia: 1107, nombre:'FRANCISCO OCHOA', idmunicipio: '73'},
    {idparroquia: 1108, nombre:'LOS CORTIJOS', idmunicipio: '73'},
    {idparroquia: 1109, nombre:'MARCIAL HERNÁNDEZ', idmunicipio: '73'},
    {idparroquia: 1110, nombre:'JOSÉ DOMINGO RUS', idmunicipio: '73'},
    {idparroquia: 1111, nombre:'SANTA RITA', idmunicipio: '74'},
    {idparroquia: 1112, nombre:'EL MENE', idmunicipio: '74'},
    {idparroquia: 1113, nombre:'JOSÉ CENOVIO URRIBARRI', idmunicipio: '74'},
    {idparroquia: 1114, nombre:'PEDRO LUCAS URRIBARRI', idmunicipio: '74'},
    {idparroquia: 1115, nombre:'MANUEL MANRIQUE', idmunicipio: '75'},
    {idparroquia: 1116, nombre:'RAFAEL MARÍA BARALT', idmunicipio: '75'},
    {idparroquia: 1117, nombre:'RAFAEL URDANETA', idmunicipio: '75'},
    {idparroquia: 1118, nombre:'BOBURES', idmunicipio: '76'},
    {idparroquia: 1119, nombre:'EL BATEY', idmunicipio: '76'},
    {idparroquia: 1120, nombre:'GIBRALTAR', idmunicipio: '76'},
    {idparroquia: 1121, nombre:'HERAS', idmunicipio: '76'},
    {idparroquia: 1122, nombre:'MONSEÑOR ARTURO CELESTINO ÁLVAREZ', idmunicipio: '76'},
    {idparroquia: 1123, nombre:'RÓMULO GALLEGOS', idmunicipio: '76'},
    {idparroquia: 1124, nombre:'LA VICTORIA', idmunicipio: '77'},
    {idparroquia: 1125, nombre:'RAFAEL URDANETA', idmunicipio: '77'},
    {idparroquia: 1126, nombre:'RAÚL CUENCA', idmunicipio: '77'},
    {idparroquia: 1127, nombre:'CARABALLEDA', idmunicipio: '78'},
    {idparroquia: 1128, nombre:'CARAYACA', idmunicipio: '78'},
    {idparroquia: 1129, nombre:'CARUAO', idmunicipio: '78'},
    {idparroquia: 1130, nombre:'CATIA LA MAR', idmunicipio: '78'},
    {idparroquia: 1131, nombre:'EL JUNKO', idmunicipio: '78'},
    {idparroquia: 1132, nombre:'LA GUAIRA', idmunicipio: '78'},
    {idparroquia: 1133, nombre:'MACUTO', idmunicipio: '78'},
    {idparroquia: 1134, nombre:'MAIQUETÍA', idmunicipio: '78'},
    {idparroquia: 1135, nombre:'NAIGUATÁ', idmunicipio: '78'},
    {idparroquia: 1136, nombre:'URIMARE', idmunicipio: '78'},
    {idparroquia: 1137, nombre:'CARLOS SOUBLETTE', idmunicipio: '78'},
    {idparroquia: 1138, nombre:'ALTAGRACIA', idmunicipio: '328'},
    {idparroquia: 1139, nombre:'ALTAGRACIA', idmunicipio: '7'},
    {idparroquia: 1140, nombre:'ALTAGRACIA', idmunicipio: '149'},
    {idparroquia: 1141, nombre:'ALTAGRACIA', idmunicipio: '70'},
    {idparroquia: 1142, nombre:'ANTIMANO', idmunicipio: '328'},
    {idparroquia: 1143, nombre:'EL PARAISO', idmunicipio: '308'},
    {idparroquia: 1145, nombre:'CAPITAL GIRARDOT', idmunicipio: '36'}
    ];
export default parroquia;